/**
 * Clinical PDF Generator
 *
 * Generates a shareable clinical progress report PDF for pediatricians and BCBAs.
 * Uses jsPDF directly (no Supabase, no AI backend needed).
 *
 * Reuses color constants and layout patterns from AIReportGenerator.tsx.
 */

import jsPDF from 'jspdf';
import type { ClinicalReportData } from './clinical-report-demo-data';
import { ASSESSMENT_INFO } from './clinical-outcomes';

// ============================================================================
// Constants (matching AIReportGenerator.tsx palette)
// ============================================================================

const AMINY_TEAL = '#0891b2';
const AMINY_GREEN = '#43AA8B';
const GRAY_800 = '#1F2937';
const GRAY_600 = '#4B5563';
const GRAY_400 = '#9CA3AF';
const GRAY_200 = '#E5E7EB';
const AMBER_50_RGB = [255, 251, 235] as const;
const AMBER_800 = '#92400E';
const GREEN_700 = '#15803d';
const RED_600 = '#dc2626';
const BLUE_600 = '#2563eb';

// ============================================================================
// Section Toggles
// ============================================================================

export interface ReportSections {
  demographics: boolean;
  medications: boolean;
  schoolInfo: boolean;
  treatmentPlan: boolean;
  goals: boolean;
  behaviorData: boolean;
  assessments: boolean;
  sessions: boolean;
  parentObservations: boolean;
  recommendations: boolean;
}

export const DEFAULT_SECTIONS: ReportSections = {
  demographics: true,
  medications: true,
  schoolInfo: true,
  treatmentPlan: true,
  goals: true,
  behaviorData: true,
  assessments: true,
  sessions: true,
  parentObservations: true,
  recommendations: true,
};

// ============================================================================
// PDF Generator
// ============================================================================

export function generateClinicalReportPDF(
  data: ClinicalReportData,
  sections: ReportSections = DEFAULT_SECTIONS,
  recipientType: 'pediatrician' | 'bcba' | 'specialist' = 'pediatrician',
): jsPDF {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  const m = 18; // margin
  const cw = pw - m * 2; // content width
  let y = m;

  // ── Helpers ──────────────────────────────────────────────

  const checkPage = (need: number = 25) => {
    if (y + need > ph - 20) {
      addFooter();
      doc.addPage();
      y = m;
      // Running header
      doc.setFontSize(8);
      doc.setTextColor(GRAY_400);
      doc.text(`${data.child.firstName} ${data.child.lastName} — Clinical Progress Report`, m, y);
      doc.text(`CONFIDENTIAL`, pw - m - 30, y);
      doc.text(`Page ${doc.getNumberOfPages()}`, pw - m, y, { align: 'right' });
      y += 8;
    }
  };

  const addFooter = () => {
    const fy = ph - 10;
    doc.setDrawColor(GRAY_200);
    doc.setLineWidth(0.3);
    doc.line(m, fy - 3, pw - m, fy - 3);
    doc.setFontSize(7);
    doc.setTextColor(GRAY_400);
    doc.text('This document contains Protected Health Information (PHI). Handle per HIPAA §164.502.', m, fy);
    doc.text(`Generated by Aminy | Page ${doc.getNumberOfPages()}`, pw - m, fy, { align: 'right' });
  };

  const sectionHeader = (title: string) => {
    checkPage(20);
    y += 4;
    doc.setDrawColor(AMINY_TEAL);
    doc.setLineWidth(0.6);
    doc.line(m, y, pw - m, y);
    y += 6;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(AMINY_TEAL);
    doc.text(title, m, y);
    y += 7;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(GRAY_600);
  };

  const labelValue = (label: string, value: string, indent: number = 0) => {
    checkPage(7);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(GRAY_800);
    doc.text(`${label}:`, m + indent, y);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(GRAY_600);
    const labelW = doc.getTextWidth(`${label}: `);
    const remaining = cw - indent - labelW;
    const lines = doc.splitTextToSize(value, remaining);
    doc.text(lines, m + indent + labelW, y);
    y += lines.length * 4.5 + 1;
  };

  const wrappedText = (text: string, indent: number = 0, fontSize: number = 9) => {
    checkPage(10);
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(GRAY_600);
    const lines = doc.splitTextToSize(text, cw - indent);
    lines.forEach((line: string) => {
      checkPage(5);
      doc.text(line, m + indent, y);
      y += 4.2;
    });
    y += 1;
  };

  const trendArrow = (trend: string): string =>
    trend === 'improving' ? '▲' : trend === 'declining' ? '▼' : '—';

  const trendColor = (trend: string) => {
    if (trend === 'improving') doc.setTextColor(GREEN_700);
    else if (trend === 'declining') doc.setTextColor(RED_600);
    else doc.setTextColor(GRAY_600);
  };

  // ── 1. Header ────────────────────────────────────────────

  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(AMINY_TEAL);
  doc.text('Aminy', m, y);
  y += 7;

  doc.setFontSize(15);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(GRAY_800);
  doc.text('Clinical Progress Report', m, y);
  y += 7;

  doc.setFontSize(9);
  doc.setTextColor(GRAY_400);
  const recipientLabel = recipientType === 'pediatrician' ? 'Pediatrician'
    : recipientType === 'bcba' ? 'BCBA / Behavior Analyst' : 'Specialist';
  doc.text(`Prepared for: ${recipientLabel}`, m, y);
  doc.text(`Report Date: ${data.reportDate}`, pw - m, y, { align: 'right' });
  y += 5;
  doc.text(`Report Period: ${data.reportPeriod.start} to ${data.reportPeriod.end}`, m, y);
  y += 8;

  // ── 2. HIPAA Notice ──────────────────────────────────────

  doc.setFillColor(...AMBER_50_RGB);
  doc.roundedRect(m, y, cw, 11, 2, 2, 'F');
  doc.setFontSize(7.5);
  doc.setTextColor(AMBER_800);
  doc.text('CONFIDENTIAL: This document contains Protected Health Information (PHI) protected under HIPAA.', m + 4, y + 4.5);
  doc.text('Intended solely for the named recipient. Do not distribute without written patient/guardian consent.', m + 4, y + 8.5);
  y += 16;

  // ── 3. Child Demographics ────────────────────────────────

  if (sections.demographics) {
    sectionHeader('Child Demographics');
    labelValue('Name', `${data.child.firstName} ${data.child.lastName}`);
    labelValue('Date of Birth', `${data.child.dateOfBirth} (Age ${data.child.age})`);
    labelValue('Gender', data.child.gender);
    labelValue('Primary Diagnosis', data.child.primaryDiagnosis);
    if (data.child.conditions.length > 1) {
      const other = data.child.conditions.slice(1).map(c =>
        c.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')
      ).join(', ');
      labelValue('Additional Conditions', other);
    }
    labelValue('Diagnosed By', data.child.diagnosingProvider);
    labelValue('Diagnosis Date', data.child.diagnosisDate);
  }

  // ── 4. Medications ───────────────────────────────────────

  if (sections.medications && data.child.medications.length > 0) {
    sectionHeader('Current Medications');
    data.child.medications.forEach(med => {
      checkPage(14);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(GRAY_800);
      doc.text(`${med.name}`, m + 2, y);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(GRAY_600);
      y += 4.5;
      doc.text(`${med.dosage} — ${med.frequency}`, m + 6, y);
      y += 4;
      doc.setFontSize(8);
      doc.setTextColor(GRAY_400);
      doc.text(`Purpose: ${med.purpose} | Prescribed by: ${med.prescribedBy}`, m + 6, y);
      y += 5.5;
    });
  }

  // ── 5. School Info ───────────────────────────────────────

  if (sections.schoolInfo && data.child.schoolInfo) {
    sectionHeader('Educational Setting');
    const si = data.child.schoolInfo;
    labelValue('School', `${si.schoolName} — Grade: ${si.grade}`);
    const supports = [
      si.hasIEP ? 'IEP' : null,
      si.has504 ? '504 Plan' : null,
      si.specialEducation ? 'Special Education Services' : null,
    ].filter(Boolean).join(', ');
    if (supports) labelValue('Supports', supports);
    if (si.mainContact) labelValue('Contact', si.mainContact);
    if (si.notes) wrappedText(si.notes, 2, 8);
  }

  // ── 6. Treatment Plan Overview ───────────────────────────

  if (sections.treatmentPlan) {
    sectionHeader('Treatment Plan Overview');
    labelValue('Service Start Date', data.treatmentPlan.startDate);
    labelValue('Approved Hours/Week', `${data.treatmentPlan.approvedHoursPerWeek}`);
    labelValue('Service Level', data.treatmentPlan.currentServiceLevel);
    labelValue('Supervising BCBA', `${data.reportingProvider.name}, ${data.reportingProvider.credentials}`);
    labelValue('Clinic', `${data.reportingProvider.clinicName} — ${data.reportingProvider.clinicPhone}`);
  }

  // ── 7. Treatment Goals & Progress ────────────────────────

  if (sections.goals) {
    sectionHeader('Treatment Goals & Progress');
    data.treatmentPlan.goals.forEach((goal, i) => {
      checkPage(35);

      // Goal header
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(GRAY_800);
      doc.text(`Goal ${i + 1}: ${goal.domain} — ${goal.title}`, m, y);
      y += 5;

      // Description
      doc.setFontSize(8.5);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(GRAY_600);
      const descLines = doc.splitTextToSize(goal.description, cw - 4);
      descLines.forEach((line: string) => {
        checkPage(5);
        doc.text(line, m + 2, y);
        y += 3.8;
      });
      y += 1;

      // Progress bar
      checkPage(12);
      const barX = m + 2;
      const barW = cw - 4;
      const barH = 4;

      // Background
      doc.setFillColor(GRAY_200);
      doc.roundedRect(barX, y, barW, barH, 1.5, 1.5, 'F');
      // Fill
      const fillW = Math.max(0, Math.min(barW, (goal.current / 100) * barW));
      const fillColor = goal.trendDirection === 'improving' ? AMINY_GREEN
        : goal.trendDirection === 'declining' ? RED_600 : BLUE_600;
      doc.setFillColor(fillColor);
      if (fillW > 0) doc.roundedRect(barX, y, fillW, barH, 1.5, 1.5, 'F');
      y += barH + 2;

      // Stats line
      doc.setFontSize(8);
      doc.setTextColor(GRAY_400);
      doc.text(`Baseline: ${goal.baseline}%`, m + 2, y);
      doc.text(`Current: ${goal.current}%`, m + cw * 0.3, y);
      doc.text(`Target: ${goal.target}%`, m + cw * 0.55, y);
      trendColor(goal.trendDirection);
      doc.text(`${trendArrow(goal.trendDirection)} ${goal.trendDirection}`, m + cw * 0.75, y);
      doc.setTextColor(GRAY_400);
      doc.text(`(${goal.dataPoints} data points)`, m + cw * 0.88, y);
      y += 4;

      // Mastery criteria
      doc.setFontSize(7.5);
      doc.setTextColor(GRAY_400);
      doc.text(`Mastery: ${goal.masteryCriteria}`, m + 2, y);
      y += 6;
    });
  }

  // ── 8. Behavioral Data Summary ───────────────────────────

  if (sections.behaviorData) {
    sectionHeader('Behavioral Data Summary');

    // Overall trend
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(GRAY_800);
    doc.text('Overall Behavioral Trend: ', m, y);
    trendColor(data.behaviorData.overallTrend);
    doc.text(`${trendArrow(data.behaviorData.overallTrend)} ${data.behaviorData.overallTrend.toUpperCase()}`, m + 45, y);
    y += 7;

    // Target behaviors table
    data.behaviorData.targetBehaviors.forEach(beh => {
      checkPage(20);

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(GRAY_800);
      doc.text(beh.name, m + 2, y);
      trendColor(beh.trend);
      doc.text(`${beh.percentChange > 0 ? '+' : ''}${beh.percentChange.toFixed(1)}%`, pw - m, y, { align: 'right' });
      y += 4;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(GRAY_600);
      const defLines = doc.splitTextToSize(beh.operationalDefinition, cw - 8);
      defLines.forEach((line: string) => {
        checkPage(4);
        doc.text(line, m + 4, y);
        y += 3.5;
      });
      y += 1;

      doc.setTextColor(GRAY_400);
      doc.text(`Baseline: ${beh.baselineRate} ${beh.unit}  →  Current: ${beh.currentRate} ${beh.unit}`, m + 4, y);
      y += 3.5;

      // Mini sparkline (text representation of 12-week trend)
      const sparkline = beh.weeklyData.map(v => {
        if (v <= 3) return '▁';
        if (v <= 6) return '▃';
        if (v <= 9) return '▅';
        if (v <= 12) return '▇';
        return '█';
      }).join(' ');
      doc.setFontSize(7);
      doc.text(`12-wk trend: ${sparkline}`, m + 4, y);
      y += 6;
    });

    // ABC function summary
    checkPage(25);
    y += 2;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(GRAY_800);
    doc.text('Antecedent Function Distribution', m, y);
    y += 5;

    data.behaviorData.abcSummary.forEach(abc => {
      checkPage(6);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(GRAY_600);
      doc.text(`${abc.antecedent}`, m + 4, y);
      doc.text(`${abc.percentage}%`, pw - m - 10, y, { align: 'right' });

      // Mini bar
      const barX2 = pw - m - 8;
      const barW2 = (abc.percentage / 100) * 50;
      doc.setFillColor(AMINY_TEAL);
      doc.rect(barX2 - 50, y - 2.5, barW2, 3, 'F');
      y += 5;
    });
  }

  // ── 9. Standardized Assessments ──────────────────────────

  if (sections.assessments && data.assessments.length > 0) {
    sectionHeader('Standardized Assessment Scores');

    data.assessments.forEach(assess => {
      checkPage(25);
      const info = ASSESSMENT_INFO[assess.type] || { name: assess.name, lowerIsBetter: false };

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(GRAY_800);
      doc.text(assess.name, m + 2, y);
      y += 4.5;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(GRAY_600);

      const scoreText = `Current Score: ${assess.score}` +
        (assess.previousScore != null ? ` (Previous: ${assess.previousScore}, Change: ${(assess.change ?? 0) > 0 ? '+' : ''}${assess.change})` : '') +
        (assess.percentile != null ? ` | Percentile: ${assess.percentile}th` : '');
      doc.text(scoreText, m + 4, y);
      y += 4;

      doc.text(`Administered: ${assess.date}${assess.previousDate ? ` (Previous: ${assess.previousDate})` : ''}`, m + 4, y);
      y += 4;

      // Interpretation
      doc.setFontSize(8);
      doc.setTextColor(GRAY_600);
      const intLines = doc.splitTextToSize(`Interpretation: ${assess.interpretation}`, cw - 8);
      intLines.forEach((line: string) => {
        checkPage(4);
        doc.text(line, m + 4, y);
        y += 3.5;
      });

      // Clinical significance indicator
      if (assess.change != null) {
        const threshold = (info as { clinicalThreshold?: number }).clinicalThreshold || 10;
        const isSignificant = Math.abs(assess.change) >= threshold;
        if (isSignificant) {
          doc.setFontSize(7.5);
          doc.setTextColor(GREEN_700);
          doc.text('✓ Clinically significant change', m + 4, y);
          y += 4;
        }
      }
      y += 3;
    });
  }

  // ── 10. Session Attendance ───────────────────────────────

  if (sections.sessions) {
    sectionHeader('Session Attendance & Service Utilization');

    // Metrics grid
    const metrics = [
      ['Total Sessions', `${data.sessions.totalSessions}`],
      ['Attended', `${data.sessions.attendedSessions}`],
      ['Attendance Rate', `${data.sessions.attendanceRate.toFixed(1)}%`],
      ['Total Hours', `${data.sessions.totalHours.toFixed(1)}`],
      ['Canceled (Family)', `${data.sessions.canceledByFamily}`],
      ['Canceled (Provider)', `${data.sessions.canceledByProvider}`],
    ];

    metrics.forEach(([label, value]) => {
      checkPage(5);
      doc.setFontSize(8.5);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(GRAY_600);
      doc.text(label, m + 4, y);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(GRAY_800);
      doc.text(value, m + 60, y);
      y += 4.5;
    });
    y += 3;

    // Hours by service type
    checkPage(15);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(GRAY_800);
    doc.text('Hours by Service Type', m, y);
    y += 5;

    Object.entries(data.sessions.hoursByType).forEach(([type, hours]) => {
      checkPage(5);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(GRAY_600);
      doc.text(type, m + 4, y);
      doc.text(`${hours} hrs`, pw - m, y, { align: 'right' });
      y += 4.5;
    });
    y += 3;

    // CPT code breakdown
    checkPage(15);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(GRAY_800);
    doc.text('Services by CPT Code', m, y);
    y += 5;

    Object.entries(data.sessions.sessionsByCPT).forEach(([code, info]) => {
      checkPage(5);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(GRAY_600);
      doc.text(`${code} — ${info.description}`, m + 4, y);
      doc.text(`${info.count} sessions (${info.units} units)`, pw - m, y, { align: 'right' });
      y += 4.5;
    });
  }

  // ── 11. Parent-Reported Observations ─────────────────────

  if (sections.parentObservations) {
    sectionHeader('Parent-Reported Observations');

    // Concerns
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(GRAY_800);
    doc.text('Current Concerns:', m, y);
    y += 5;

    data.parentReport.concerns.forEach(concern => {
      checkPage(10);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(GRAY_600);
      const lines = doc.splitTextToSize(`• ${concern}`, cw - 8);
      lines.forEach((line: string) => {
        checkPage(4);
        doc.text(line, m + 4, y);
        y += 3.8;
      });
      y += 1;
    });
    y += 2;

    // Wins
    checkPage(10);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(GRAY_800);
    doc.text('Recent Wins & Milestones:', m, y);
    y += 5;

    data.parentReport.wins.forEach(win => {
      checkPage(10);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(GRAY_600);
      const lines = doc.splitTextToSize(`✓ ${win}`, cw - 8);
      lines.forEach((line: string) => {
        checkPage(4);
        doc.text(line, m + 4, y);
        y += 3.8;
      });
      y += 1;
    });
    y += 2;

    // Home environment
    checkPage(12);
    labelValue('Home Environment', data.parentReport.homeEnvironmentNotes);
    if (data.parentReport.medicationChanges) {
      labelValue('Medication Changes', data.parentReport.medicationChanges);
    }
    if (data.parentReport.recentLifeEvents) {
      labelValue('Recent Life Events', data.parentReport.recentLifeEvents);
    }
  }

  // ── 12. Clinical Recommendations ─────────────────────────

  if (sections.recommendations) {
    sectionHeader('Clinical Recommendations');

    data.recommendations.forEach((rec, i) => {
      checkPage(10);
      doc.setFontSize(8.5);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(GRAY_600);
      const lines = doc.splitTextToSize(`${i + 1}. ${rec}`, cw - 8);
      lines.forEach((line: string) => {
        checkPage(4);
        doc.text(line, m + 2, y);
        y += 4;
      });
      y += 2;
    });
  }

  // ── 13. Signature Block ──────────────────────────────────

  checkPage(50);
  y += 6;
  doc.setDrawColor(GRAY_200);
  doc.setLineWidth(0.5);
  doc.line(m, y, pw - m, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(GRAY_800);
  doc.text('Provider Certification', m, y);
  y += 8;

  // BCBA signature line
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(GRAY_600);
  doc.text('Supervising BCBA:', m, y);
  y += 10;
  doc.setDrawColor(GRAY_800);
  doc.setLineWidth(0.3);
  doc.line(m, y, m + 70, y);
  doc.line(m + 80, y, m + 120, y);
  y += 4;
  doc.setFontSize(7.5);
  doc.setTextColor(GRAY_400);
  doc.text('Signature', m, y);
  doc.text('Date', m + 80, y);
  y += 6;

  doc.setFontSize(8);
  doc.setTextColor(GRAY_600);
  doc.text(`${data.reportingProvider.name}, ${data.reportingProvider.credentials}`, m, y);
  y += 3.5;
  doc.text(`License: ${data.reportingProvider.licenseNumber} | NPI: ${data.reportingProvider.npi}`, m, y);
  y += 3.5;
  doc.text(`${data.reportingProvider.clinicName}`, m, y);
  y += 3.5;
  doc.text(`${data.reportingProvider.clinicAddress}`, m, y);
  y += 8;

  if (data.reportingProvider.supervisorName) {
    doc.setFontSize(8);
    doc.setTextColor(GRAY_600);
    doc.text(`Clinical Director: ${data.reportingProvider.supervisorName}, ${data.reportingProvider.supervisorCredentials}`, m, y);
    y += 6;
  }

  // Referring provider acknowledgment
  y += 4;
  doc.setFontSize(9);
  doc.setTextColor(GRAY_600);
  doc.text('Referring Provider Acknowledgment:', m, y);
  y += 10;
  doc.line(m, y, m + 70, y);
  doc.line(m + 80, y, m + 120, y);
  y += 4;
  doc.setFontSize(7.5);
  doc.setTextColor(GRAY_400);
  doc.text('Signature', m, y);
  doc.text('Date', m + 80, y);

  // ── Final footer ─────────────────────────────────────────
  addFooter();

  return doc;
}
