/**
 * Aminy Microcopy Library - ABA-Based Behavioral Wellness
 * 
 * This library provides brand-compliant microcopy for tooltips, buttons,
 * notifications, and UI elements throughout the app.
 * 
 * All copy follows the ABA + AI wellness framework:
 * - Empathy + Intelligence + Progress
 * - Warm-expert tone
 * - Pairs ABA with AI
 * - Avoids clinical language
 */

import { getRandomMessage } from './brand-guide';

// ============================================================================
// NOTIFICATIONS & TOASTS
// ============================================================================

export const TOAST_MESSAGES = {
  // Success messages
  success: {
    planCreated: "Your calm plan is ready! Let's start with one small win.",
    goalCompleted: "Great job! That's progress we can celebrate together.",
    routineCompleted: "Routine complete! Consistency builds comfort.",
    reportGenerated: "Your progress report is ready to share.",
    activityCompleted: "Activity complete! You're building something beautiful.",
    progressSaved: "Progress saved — every step counts.",
    profileUpdated: "Profile updated successfully.",
    settingsSaved: "Settings saved — we're learning your family's rhythm."
  },
  
  // Encouraging progress messages
  progress: {
    streakContinued: "Streak continues! That's positive reinforcement in action.",
    firstActivity: "First activity complete! Small wins add up to big calm.",
    weeklyGoalMet: "Weekly goal met! You're showing up and it's working.",
    milestoneReached: "Milestone reached — take a moment to celebrate this win.",
    consistencyBuilding: "3 days in a row! Consistency builds comfort and trust."
  },
  
  // Gentle errors (ABA wellness tone)
  error: {
    generic: "Oops! Let's try that again. Take a breath — we've got this.",
    networkIssue: "Connection hiccup. Give it a moment and we'll reconnect.",
    saveFailed: "Couldn't save just now. Your work is safe — let's retry.",
    loadFailed: "Having trouble loading. Hang tight while we figure it out.",
    unauthorized: "Please sign in to access this feature.",
    upgradeRequired: "This feature is available in Core and Plus plans."
  },
  
  // Info messages
  info: {
    saving: "Saving your progress...",
    syncing: "Syncing with Aminy's AI...",
    analyzing: "Analyzing patterns with ABA science...",
    generating: "Generating personalized guidance...",
    loading: "Loading your calm plan..."
  }
};

// ============================================================================
// BUTTON LABELS
// ============================================================================

export const BUTTON_LABELS = {
  // Primary actions
  start: "Start now",
  continue: "Continue",
  save: "Save progress",
  complete: "Mark complete",
  next: "Next step",
  finish: "Finish",
  done: "Done",
  
  // Calm plan & activities
  startPlan: "Start your calm plan",
  viewPlan: "View today's plan",
  addActivity: "Add activity",
  startActivity: "Start activity",
  completeActivity: "Complete",
  skipActivity: "Skip for now",
  
  // AI & Coach
  askAminy: "Ask Aminy",
  startChat: "Start conversation",
  talkToAminy: "Talk to Aminy",
  getGuidance: "Get AI guidance",
  analyzeProgress: "Analyze progress",
  
  // Reports & Sharing
  generateReport: "Generate report",
  downloadReport: "Download",
  shareReport: "Share progress",
  viewReport: "View report",
  
  // Account & Settings
  saveSettings: "Save settings",
  updateProfile: "Update profile",
  manageSubscription: "Manage plan",
  upgrade: "Upgrade plan",
  
  // Social proof / conversion
  startFreeTrial: "Start free 7-day trial",
  buildCalmPlan: "Build my calm plan",
  seeHowItWorks: "See how it works",
  experienceABA: "Experience ABA-based calm"
};

// ============================================================================
// TOOLTIPS & HELP TEXT
// ============================================================================

export const TOOLTIPS = {
  // AI features
  aiGuidance: "Aminy uses adaptive AI and ABA principles to personalize guidance for your family.",
  adaptivePlan: "Your plan learns and adjusts based on what's working — powered by behavioral science.",
  progressTracking: "Track meaningful progress with ABA metrics, no clinical jargon.",
  
  // Features
  streakCounter: "Consistency builds comfort! Keep your streak going.",
  visualSchedule: "Visual cues help create predictable routines.",
  reinforcement: "Positive reinforcement celebrates what's working.",
  gentleCues: "Gentle prompts support calm transitions.",
  
  // Reports & Data
  privacyFirst: "Your data supports your family's progress — never sold, always private.",
  shareableReports: "Generated by AI, grounded in ABA science — ready to share with providers.",
  expiringLinks: "Shareable for 7 days to protect your family's privacy.",
  
  // Tiers & Plans
  coreFeatures: "Everything you need to create calm, with unlimited AI support.",
  plusFeatures: "Full support with live telehealth and professional documentation.",
  starterFeatures: "Basic support to test if Aminy fits your family."
};

// ============================================================================
// EMPTY STATES
// ============================================================================

export const EMPTY_STATES = {
  noPlan: {
    title: "Your calm plan is almost ready",
    message: "Let's build a personalized routine using ABA principles — it takes just 3 minutes.",
    cta: "Build my plan"
  },
  
  noActivities: {
    title: "No activities yet",
    message: "Start your first activity to begin building calm, consistent routines.",
    cta: "Start activity"
  },
  
  noReports: {
    title: "No reports yet",
    message: "Generate your first report to see progress backed by ABA science.",
    cta: "Generate report"
  },
  
  noGoals: {
    title: "Ready to set a goal?",
    message: "Let Aminy help you break it down into gentle, achievable steps.",
    cta: "Add goal"
  },
  
  noMessages: {
    title: "Start a conversation",
    message: "Ask Aminy anything — from daily support to coverage questions.",
    cta: "Start chat"
  }
};

// ============================================================================
// LOADING STATES
// ============================================================================

export const LOADING_STATES = {
  analyzing: "Analyzing patterns with ABA science...",
  generating: "Generating your personalized plan...",
  adapting: "Adapting to your family's rhythm...",
  learning: "Learning what works best...",
  creating: "Creating calm routines...",
  building: "Building your progress report...",
  thinking: "Aminy is thinking...",
  processing: "Processing with behavioral insights..."
};

// ============================================================================
// PROGRESS INDICATORS
// ============================================================================

export const PROGRESS_MESSAGES = {
  onboarding: {
    step1: "Getting to know you...",
    step2: "Understanding your goals...",
    step3: "Building your calm plan...",
    step4: "Almost there...",
    complete: "Your plan is ready!"
  },
  
  activity: {
    notStarted: "Ready to start",
    inProgress: "In progress — you've got this",
    nearlyDone: "Almost there!",
    complete: "Complete! That's a win to celebrate."
  },
  
  goal: {
    noProgress: "Let's take the first step together",
    started: "Progress started — small wins matter",
    halfwayThere: "Halfway there! Keep going.",
    almostDone: "Almost there — you're doing great",
    complete: "Goal achieved! Time to celebrate this win."
  }
};

// ============================================================================
// CONTEXTUAL NUDGES
// ============================================================================

export const NUDGES = {
  morningRoutine: {
    message: "Mornings have been smoother this week! That's ABA reinforcement working.",
    action: "View progress"
  },
  
  missedActivity: {
    message: "No stress — let's adjust today's plan to what feels doable.",
    action: "Adjust plan"
  },
  
  streakAtRisk: {
    message: "One quick activity keeps your 5-day streak going!",
    action: "Quick win"
  },
  
  newFeature: {
    message: "New: AI can now generate progress reports to share with providers.",
    action: "Try it"
  },
  
  encouragement: {
    message: "You showed up 4 days this week. That consistency builds real change.",
    action: "See insights"
  },
  
  insuranceReminder: {
    message: "Your insurance might cover ABA services. Want to check?",
    action: "Check coverage"
  }
};

// ============================================================================
// FORM VALIDATION MESSAGES
// ============================================================================

export const VALIDATION = {
  required: "This field is needed to personalize your plan.",
  email: "Please enter a valid email address.",
  password: "Password must be at least 8 characters.",
  childName: "What should we call your little one?",
  childAge: "This helps us personalize age-appropriate activities.",
  tooShort: "Tell us a bit more — every detail helps.",
  invalidDate: "Please enter a valid date.",
  futureDate: "This date looks like it's in the future.",
  pastDate: "This date needs to be in the past."
};

// ============================================================================
// CONFIRMATION MESSAGES
// ============================================================================

export const CONFIRMATIONS = {
  deleteActivity: {
    title: "Remove this activity?",
    message: "This won't affect your progress — you can always add it back.",
    confirm: "Remove",
    cancel: "Keep it"
  },
  
  deleteGoal: {
    title: "Archive this goal?",
    message: "Your progress will be saved — this just moves it out of your active plan.",
    confirm: "Archive",
    cancel: "Keep active"
  },
  
  resetStreak: {
    title: "Start fresh?",
    message: "No worries — every day is a new chance to build consistency.",
    confirm: "Reset",
    cancel: "Cancel"
  },
  
  cancelSubscription: {
    title: "Pause your plan?",
    message: "Your data stays safe. You can come back anytime.",
    confirm: "Pause subscription",
    cancel: "Keep my plan"
  },
  
  deleteReport: {
    title: "Delete this report?",
    message: "You can always generate a new one with updated progress.",
    confirm: "Delete",
    cancel: "Keep"
  }
};

// ============================================================================
// SECTION HEADERS & DESCRIPTIONS
// ============================================================================

export const SECTIONS = {
  dashboard: {
    title: "Today's Calm Plan",
    subtitle: "Powered by adaptive AI and ABA behavioral science"
  },
  
  plan: {
    title: "Your Personalized Plan",
    subtitle: "Built on ABA principles, adapted to your family's rhythm"
  },
  
  reports: {
    title: "Progress You Can See",
    subtitle: "AI-generated, grounded in behavioral science"
  },
  
  coach: {
    title: "Ask Aminy",
    subtitle: "Your AI companion for behavioral wellness guidance"
  },
  
  vault: {
    title: "Your Family Vault",
    subtitle: "Secure storage for reports, evaluations, and progress docs"
  },
  
  settings: {
    title: "Settings",
    subtitle: "Personalize how Aminy supports your family"
  }
};

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Get a random success message
 */
export function getSuccessMessage(category?: keyof typeof TOAST_MESSAGES.success): string {
  if (category && TOAST_MESSAGES.success[category]) {
    return TOAST_MESSAGES.success[category];
  }
  const messages = Object.values(TOAST_MESSAGES.success);
  return messages[Math.floor(Math.random() * messages.length)];
}

/**
 * Get a random progress message
 */
export function getProgressMessage(category?: keyof typeof TOAST_MESSAGES.progress): string {
  if (category && TOAST_MESSAGES.progress[category]) {
    return TOAST_MESSAGES.progress[category];
  }
  const messages = Object.values(TOAST_MESSAGES.progress);
  return messages[Math.floor(Math.random() * messages.length)];
}

/**
 * Get contextual loading message
 */
export function getLoadingMessage(context?: 'analyzing' | 'generating' | 'adapting' | 'learning' | 'creating' | 'building'): string {
  return context && LOADING_STATES[context] 
    ? LOADING_STATES[context] 
    : LOADING_STATES.thinking;
}

/**
 * Get appropriate CTA based on context
 */
export function getCTA(context: 'start' | 'continue' | 'complete' | 'save'): string {
  const ctas = {
    start: BUTTON_LABELS.start,
    continue: BUTTON_LABELS.continue,
    complete: BUTTON_LABELS.complete,
    save: BUTTON_LABELS.save
  };
  return ctas[context];
}
