/**
 * Referral Packet PDF Generator
 *
 * Generates a comprehensive PDF packet for sharing with local providers.
 * Includes: concern summary, parent goals, routines, progress snapshots,
 * visit summaries, and action items.
 *
 * Uses jsPDF for client-side PDF generation.
 */

import jsPDF from 'jspdf';

// ============================================================================
// Types
// ============================================================================

export interface ReferralPacketData {
  // Child/Family Info
  childName: string;
  childAge: string;
  parentName: string;
  generatedDate: string;

  // Primary Concern
  concernSummary: string;
  concernCategory: string;
  urgencyLevel: 'routine' | 'soon' | 'urgent';

  // Parent Goals
  parentGoals: string[];

  // Daily Routines
  routines: {
    morning: string;
    afternoon: string;
    evening: string;
    challenges: string[];
  };

  // Progress Snapshots (if available)
  progressSnapshots?: {
    metric: string;
    currentValue: string;
    trend: 'improving' | 'stable' | 'declining';
    notes?: string;
  }[];

  // Visit Summaries (if any)
  visitSummaries?: {
    date: string;
    providerName: string;
    providerCredentials: string;
    reasonForVisit: string;
    keyDiscussions: string[];
    actionItems: string[];
  }[];

  // Consent
  consentToShare: boolean;
  consentDate?: string;
}

// ============================================================================
// PDF Generation
// ============================================================================

const AMINY_BLUE = '#577590';
const AMINY_GREEN = '#43AA8B';
const GRAY_600 = '#4B5563';
const GRAY_400 = '#9CA3AF';

export function generateReferralPacketPDF(data: ReferralPacketData): jsPDF {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);
  let yPos = margin;

  // Helper: Add new page if needed
  const checkPageBreak = (neededSpace: number) => {
    if (yPos + neededSpace > pageHeight - margin) {
      doc.addPage();
      yPos = margin;
      addHeader();
    }
  };

  // Helper: Add header to each page
  const addHeader = () => {
    doc.setFontSize(10);
    doc.setTextColor(GRAY_400);
    doc.text('Aminy Provider Packet', margin, 10);
    doc.text(`Generated: ${data.generatedDate}`, pageWidth - margin, 10, { align: 'right' });
    doc.setDrawColor(GRAY_400);
    doc.line(margin, 14, pageWidth - margin, 14);
  };

  // Helper: Section header
  const addSectionHeader = (title: string) => {
    checkPageBreak(15);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(AMINY_BLUE);
    doc.text(title, margin, yPos);
    yPos += 8;
  };

  // Helper: Add text block
  const addText = (text: string, indent = 0) => {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(GRAY_600);
    const lines = doc.splitTextToSize(text, contentWidth - indent);
    checkPageBreak(lines.length * 5 + 2);
    doc.text(lines, margin + indent, yPos);
    yPos += lines.length * 5 + 2;
  };

  // Helper: Add bullet list
  const addBulletList = (items: string[], indent = 5) => {
    items.forEach(item => {
      const lines = doc.splitTextToSize(`• ${item}`, contentWidth - indent - 5);
      checkPageBreak(lines.length * 5 + 2);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(GRAY_600);
      doc.text(lines, margin + indent, yPos);
      yPos += lines.length * 5 + 2;
    });
  };

  // =========================================================================
  // Page 1: Cover & Summary
  // =========================================================================

  // Aminy Logo/Title
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(AMINY_BLUE);
  doc.text('Aminy', margin, yPos);
  yPos += 8;

  doc.setFontSize(18);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(GRAY_600);
  doc.text('Provider-Ready Referral Packet', margin, yPos);
  yPos += 15;

  // Watermark notice
  doc.setFillColor(245, 245, 245);
  doc.roundedRect(margin, yPos, contentWidth, 12, 2, 2, 'F');
  doc.setFontSize(9);
  doc.setTextColor(GRAY_400);
  doc.text(`This packet was generated by Aminy on ${data.generatedDate}. For questions, contact support@aminy.com`, margin + 5, yPos + 7);
  yPos += 20;

  // Child/Family Overview Box
  doc.setDrawColor(AMINY_BLUE);
  doc.setLineWidth(0.5);
  doc.roundedRect(margin, yPos, contentWidth, 35, 3, 3, 'S');

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(AMINY_BLUE);
  doc.text('Child & Family Overview', margin + 5, yPos + 8);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(GRAY_600);
  doc.text(`Child: ${data.childName} (${data.childAge})`, margin + 5, yPos + 16);
  doc.text(`Parent/Caregiver: ${data.parentName}`, margin + 5, yPos + 23);
  doc.text(`Primary Concern: ${data.concernCategory}`, margin + 5, yPos + 30);

  // Urgency badge
  const urgencyColors = {
    routine: '#22C55E',
    soon: '#F59E0B',
    urgent: '#EF4444'
  };
  const urgencyLabels = {
    routine: 'Routine',
    soon: 'Soon',
    urgent: 'Urgent'
  };
  doc.setFillColor(urgencyColors[data.urgencyLevel]);
  doc.roundedRect(pageWidth - margin - 25, yPos + 5, 20, 6, 1, 1, 'F');
  doc.setFontSize(8);
  doc.setTextColor(255, 255, 255);
  doc.text(urgencyLabels[data.urgencyLevel], pageWidth - margin - 23, yPos + 9);

  yPos += 45;

  // =========================================================================
  // Primary Concern Summary
  // =========================================================================
  addSectionHeader('Primary Concern');
  addText(data.concernSummary);
  yPos += 5;

  // =========================================================================
  // Parent Goals
  // =========================================================================
  addSectionHeader('Parent Goals');
  if (data.parentGoals.length > 0) {
    addBulletList(data.parentGoals);
  } else {
    addText('No specific goals documented yet.');
  }
  yPos += 5;

  // =========================================================================
  // Daily Routines
  // =========================================================================
  addSectionHeader('Daily Routines');

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(GRAY_600);
  doc.text('Morning:', margin, yPos);
  yPos += 5;
  addText(data.routines.morning, 5);

  doc.setFont('helvetica', 'bold');
  doc.text('Afternoon:', margin, yPos);
  yPos += 5;
  addText(data.routines.afternoon, 5);

  doc.setFont('helvetica', 'bold');
  doc.text('Evening:', margin, yPos);
  yPos += 5;
  addText(data.routines.evening, 5);

  if (data.routines.challenges.length > 0) {
    yPos += 3;
    doc.setFont('helvetica', 'bold');
    doc.text('Key Challenges:', margin, yPos);
    yPos += 5;
    addBulletList(data.routines.challenges, 5);
  }
  yPos += 5;

  // =========================================================================
  // Progress Snapshots (if available)
  // =========================================================================
  if (data.progressSnapshots && data.progressSnapshots.length > 0) {
    addSectionHeader('Progress Snapshots');

    data.progressSnapshots.forEach(snapshot => {
      checkPageBreak(20);

      const trendSymbol = {
        improving: '+',
        stable: '=',
        declining: '-'
      };
      const trendColor = {
        improving: AMINY_GREEN,
        stable: GRAY_400,
        declining: '#EF4444'
      };

      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(GRAY_600);
      doc.text(`${snapshot.metric}:`, margin, yPos);

      doc.setFont('helvetica', 'normal');
      doc.text(snapshot.currentValue, margin + 50, yPos);

      doc.setTextColor(trendColor[snapshot.trend]);
      doc.text(`(${trendSymbol[snapshot.trend]} ${snapshot.trend})`, margin + 80, yPos);

      yPos += 6;

      if (snapshot.notes) {
        doc.setFontSize(10);
        doc.setTextColor(GRAY_400);
        doc.text(snapshot.notes, margin + 5, yPos);
        yPos += 5;
      }
    });
    yPos += 5;
  }

  // =========================================================================
  // Visit Summaries (if available)
  // =========================================================================
  if (data.visitSummaries && data.visitSummaries.length > 0) {
    addSectionHeader('Telehealth Visit Summaries');

    data.visitSummaries.forEach((visit, index) => {
      checkPageBreak(40);

      // Visit header box
      doc.setFillColor(248, 250, 252);
      doc.roundedRect(margin, yPos, contentWidth, 10, 2, 2, 'F');

      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(AMINY_BLUE);
      doc.text(`Visit ${index + 1}: ${visit.date}`, margin + 3, yPos + 7);

      doc.setFont('helvetica', 'normal');
      doc.setTextColor(GRAY_600);
      doc.text(`${visit.providerName}, ${visit.providerCredentials}`, pageWidth - margin - 3, yPos + 7, { align: 'right' });

      yPos += 15;

      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text('Reason for Visit:', margin, yPos);
      yPos += 5;
      addText(visit.reasonForVisit, 3);

      if (visit.keyDiscussions.length > 0) {
        doc.setFont('helvetica', 'bold');
        doc.text('Key Discussions:', margin, yPos);
        yPos += 5;
        addBulletList(visit.keyDiscussions, 3);
      }

      if (visit.actionItems.length > 0) {
        doc.setFont('helvetica', 'bold');
        doc.text('Action Items:', margin, yPos);
        yPos += 5;
        addBulletList(visit.actionItems, 3);
      }

      yPos += 8;
    });
  }

  // =========================================================================
  // Consent Footer
  // =========================================================================
  checkPageBreak(25);
  yPos += 5;

  doc.setDrawColor(AMINY_GREEN);
  doc.setLineWidth(0.3);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(AMINY_GREEN);
  doc.text('Consent to Share', margin, yPos);
  yPos += 5;

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(GRAY_600);
  if (data.consentToShare && data.consentDate) {
    doc.text(`Parent/caregiver consented to share this packet on ${data.consentDate}.`, margin, yPos);
  } else {
    doc.text('Consent to share pending.', margin, yPos);
  }
  yPos += 8;

  doc.setFontSize(9);
  doc.setTextColor(GRAY_400);
  const disclaimer = 'This document is for informational purposes only and does not constitute a diagnosis or medical advice. ' +
    'Information shared is based on parent-reported data and telehealth consultations. ' +
    'Please use clinical judgment when incorporating this information into care planning.';
  const disclaimerLines = doc.splitTextToSize(disclaimer, contentWidth);
  doc.text(disclaimerLines, margin, yPos);

  // Add page numbers
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(GRAY_400);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
  }

  return doc;
}

/**
 * Generate and download the referral packet PDF
 */
export function downloadReferralPacketPDF(data: ReferralPacketData, filename?: string): void {
  const doc = generateReferralPacketPDF(data);
  const defaultFilename = `aminy-referral-packet-${data.childName.replace(/\s+/g, '-').toLowerCase()}-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename || defaultFilename);
}

/**
 * Generate PDF and return as blob for sharing
 */
export function getReferralPacketBlob(data: ReferralPacketData): Blob {
  const doc = generateReferralPacketPDF(data);
  return doc.output('blob');
}

/**
 * Create sample/demo packet data
 */
export function createSamplePacketData(): ReferralPacketData {
  return {
    childName: 'Sample Child',
    childAge: '4 years old',
    parentName: 'Sample Parent',
    generatedDate: new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    }),
    concernSummary: 'Child experiences frequent meltdowns during transitions, particularly in the morning routine and when leaving preferred activities. Sensory sensitivities to loud noises and certain textures have been noted. Parent is seeking strategies to reduce meltdown frequency and improve transition success.',
    concernCategory: 'Meltdowns / Aggression',
    urgencyLevel: 'soon',
    parentGoals: [
      'Reduce morning routine meltdowns from daily to 2-3x per week',
      'Develop visual supports for transitions',
      'Learn proactive strategies for sensory regulation',
      'Build a consistent bedtime routine'
    ],
    routines: {
      morning: 'Wake at 7am, breakfast at 7:30. Struggles with getting dressed and brushing teeth. Usually leaves for school around 8:15 but often late due to meltdowns.',
      afternoon: 'Returns from school at 3pm. Needs decompression time. Snack, then homework/play. Transitions to dinner around 5:30.',
      evening: 'Dinner at 6pm. Bath time is challenging. Bedtime routine starts at 7:30, in bed by 8pm but often takes 30+ minutes to fall asleep.',
      challenges: [
        'Transition from preferred activities (screen time, play)',
        'Getting dressed - texture sensitivities with certain fabrics',
        'Tooth brushing - sensory aversion',
        'Unexpected changes to routine'
      ]
    },
    progressSnapshots: [
      {
        metric: 'Daily Meltdowns',
        currentValue: '2-3 per day',
        trend: 'stable',
        notes: 'Tracking for 2 weeks'
      },
      {
        metric: 'Successful Transitions',
        currentValue: '4 of 8 daily',
        trend: 'improving',
        notes: 'Up from 2 of 8 last week'
      }
    ],
    visitSummaries: [
      {
        date: 'January 10, 2026',
        providerName: 'Sarah Chen',
        providerCredentials: 'BCBA, LBA',
        reasonForVisit: 'Initial consultation for meltdown management',
        keyDiscussions: [
          'Identified triggers: sudden changes and sensory overwhelm',
          'Current routine review showed gaps in visual supports',
          'Discussed proactive strategies vs reactive responses'
        ],
        actionItems: [
          'Create a visual schedule for morning routine',
          'Give 5-minute and 2-minute warnings before transitions',
          'Practice "First-Then" language during calm moments'
        ]
      }
    ],
    consentToShare: true,
    consentDate: new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    })
  };
}
