import { chromium } from 'playwright';
const OUT = '/tmp/claude-0/-home-user-Aminy-Final/9f362c82-800d-52d6-9e73-87548098b442/scratchpad/fixed2';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage({ viewport: { width: 375, height: 812 } });
await page.goto('http://localhost:3000', { waitUntil: 'domcontentloaded' });
await page.waitForFunction(() => typeof window.__navigateToScreen === 'function', { timeout: 30000 });
await page.waitForTimeout(2000);
const essential = page.getByRole('button', { name: /essential only/i });
if (await essential.count()) await essential.first().click().catch(() => {});
await page.evaluate(() => window.__navigateToScreen('ask-aminy'));
await page.waitForTimeout(2500);
const info = await page.evaluate(() => {
  const card = [...document.querySelectorAll('button')].find(b => b.textContent.includes('Create a care plan'));
  const row = card?.closest('.overflow-x-auto');
  if (!row) return { found: false };
  const before = row.scrollLeft;
  row.scrollLeft = 9999;
  return { found: true, before, after: row.scrollLeft, scrollWidth: row.scrollWidth, clientWidth: row.clientWidth };
});
console.log(JSON.stringify(info));
await page.waitForTimeout(500);
await page.screenshot({ path: `${OUT}/ask-aminy-scrolled.png` });
await browser.close();
