import { chromium } from '@playwright/test';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage({ viewport: { width: 375, height: 812 } });
page.on('console', m => { if (['error','warning'].includes(m.type())) console.log('[console]', m.type(), m.text().slice(0,300)); });
page.on('pageerror', e => console.log('[pageerror]', String(e).slice(0,500)));
await page.goto('http://localhost:3000/', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(8000);
console.log('nav fn:', await page.evaluate(() => typeof window.__navigateToScreen));
console.log('body text head:', (await page.evaluate(() => document.body.innerText.slice(0,200))));
await browser.close();
