import { chromium } from 'playwright';
const OUT = '/tmp/claude-0/-home-user-Aminy-Final/9f362c82-800d-52d6-9e73-87548098b442/scratchpad/fixed4';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage({ viewport: { width: 375, height: 812 } });
await page.goto('http://localhost:3000', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(4000);
await page.evaluate(() => window.__navigateToScreen('profile'));
await page.waitForTimeout(2200);
await page.screenshot({ path: `${OUT}/profile.png` });
await page.evaluate(() => window.__navigateToScreen('wins-journal'));
await page.waitForTimeout(7500);
await page.screenshot({ path: `${OUT}/wins-journal-after6s.png` });
await browser.close();
console.log('done');
