// ---------------------------------------------------------------------------
// Feelscape Sound Library — Sound Definitions
// 35 procedurally-generated ambient sounds across 6 categories
// ---------------------------------------------------------------------------

export type SoundCategory = 'nature' | 'white-noise' | 'animals' | 'music' | 'ambience' | 'haptics';

export interface SoundDefinition {
  id: string;
  name: string;
  category: SoundCategory;
  emoji: string;
  type: 'feelscape' | 'haptic';
  premium: boolean;
  /** CSS gradient for the card background (inline style, not Tailwind arbitrary) */
  gradientFrom: string;
  gradientTo: string;
  /** Web Audio generation strategy */
  generatorType: 'noise' | 'oscillator' | 'combined' | 'haptic-only';
  generatorConfig: Record<string, number>;
}

export const SOUND_CATEGORIES: { id: SoundCategory | 'favorites'; label: string; emoji: string }[] = [
  { id: 'favorites', label: 'Favorites', emoji: '\u2764\uFE0F' },
  { id: 'nature', label: 'Nature', emoji: '\uD83C\uDF3F' },
  { id: 'white-noise', label: 'White Noise', emoji: '\uD83C\uDF2B\uFE0F' },
  { id: 'animals', label: 'Animals', emoji: '\uD83D\uDC3E' },
  { id: 'music', label: 'Music', emoji: '\uD83C\uDFB5' },
  { id: 'ambience', label: 'Ambience', emoji: '\u2728' },
  { id: 'haptics', label: 'Haptics', emoji: '\uD83D\uDCF3' },
];

export const SOUNDS: SoundDefinition[] = [
  // ── Nature (8) ──────────────────────────────────────────────
  {
    id: 'rain',
    name: 'Rain',
    category: 'nature',
    emoji: '\uD83C\uDF27\uFE0F',
    type: 'feelscape',
    premium: false,
    gradientFrom: '#4a6fa5',
    gradientTo: '#7eb8da',
    generatorType: 'noise',
    generatorConfig: { lowFreq: 800, highFreq: 2000, ampMod: 0.3, ampModFreq: 0.15 },
  },
  {
    id: 'thunder',
    name: 'Thunder',
    category: 'nature',
    emoji: '\u26C8\uFE0F',
    type: 'feelscape',
    premium: false,
    gradientFrom: '#2c3e50',
    gradientTo: '#636e72',
    generatorType: 'combined',
    generatorConfig: { lowFreq: 60, highFreq: 120, burstInterval: 8, burstDuration: 2 },
  },
  {
    id: 'ocean-waves',
    name: 'Ocean Waves',
    category: 'nature',
    emoji: '\uD83C\uDF0A',
    type: 'feelscape',
    premium: false,
    gradientFrom: '#0077b6',
    gradientTo: '#90e0ef',
    generatorType: 'noise',
    generatorConfig: { lowFreq: 200, highFreq: 1200, ampMod: 0.8, ampModFreq: 0.08 },
  },
  {
    id: 'river',
    name: 'River',
    category: 'nature',
    emoji: '\uD83C\uDFDE\uFE0F',
    type: 'feelscape',
    premium: false,
    gradientFrom: '#48cae4',
    gradientTo: '#ade8f4',
    generatorType: 'noise',
    generatorConfig: { lowFreq: 600, highFreq: 3000, ampMod: 0.2, ampModFreq: 0.5 },
  },
  {
    id: 'waterfall',
    name: 'Waterfall',
    category: 'nature',
    emoji: '\uD83D\uDCA7',
    type: 'feelscape',
    premium: true,
    gradientFrom: '#219ebc',
    gradientTo: '#8ecae6',
    generatorType: 'noise',
    generatorConfig: { lowFreq: 100, highFreq: 4000, ampMod: 0.1, ampModFreq: 0.05 },
  },
  {
    id: 'campfire',
    name: 'Campfire',
    category: 'nature',
    emoji: '\uD83D\uDD25',
    type: 'feelscape',
    premium: false,
    gradientFrom: '#e76f51',
    gradientTo: '#f4a261',
    generatorType: 'combined',
    generatorConfig: { lowFreq: 500, highFreq: 5000, crackleRate: 12, crackleDecay: 0.03 },
  },
  {
    id: 'wind',
    name: 'Wind',
    category: 'nature',
    emoji: '\uD83D\uDCA8',
    type: 'feelscape',
    premium: false,
    gradientFrom: '#a8dadc',
    gradientTo: '#e9ecef',
    generatorType: 'noise',
    generatorConfig: { lowFreq: 200, highFreq: 800, ampMod: 0.5, ampModFreq: 0.12 },
  },
  {
    id: 'jungle',
    name: 'Jungle',
    category: 'nature',
    emoji: '\uD83C\uDF34',
    type: 'feelscape',
    premium: true,
    gradientFrom: '#2d6a4f',
    gradientTo: '#52b788',
    generatorType: 'combined',
    generatorConfig: { lowFreq: 1000, highFreq: 4000, chirpRate: 3, chirpDuration: 0.15 },
  },

  // ── White Noise (5) ────────────────────────────────────────
  {
    id: 'white-noise',
    name: 'White Noise',
    category: 'white-noise',
    emoji: '\u2601\uFE0F',
    type: 'feelscape',
    premium: false,
    gradientFrom: '#dee2e6',
    gradientTo: '#f8f9fa',
    generatorType: 'noise',
    generatorConfig: { lowFreq: 20, highFreq: 20000, ampMod: 0, ampModFreq: 0 },
  },
  {
    id: 'pink-noise',
    name: 'Pink Noise',
    category: 'white-noise',
    emoji: '\uD83C\uDF38',
    type: 'feelscape',
    premium: false,
    gradientFrom: '#ffafcc',
    gradientTo: '#ffc8dd',
    generatorType: 'noise',
    generatorConfig: { lowFreq: 20, highFreq: 20000, ampMod: 0, ampModFreq: 0, pink: 1 },
  },
  {
    id: 'brown-noise',
    name: 'Brown Noise',
    category: 'white-noise',
    emoji: '\uD83E\uDEB5',
    type: 'feelscape',
    premium: false,
    gradientFrom: '#8d6e63',
    gradientTo: '#bcaaa4',
    generatorType: 'noise',
    generatorConfig: { lowFreq: 20, highFreq: 20000, ampMod: 0, ampModFreq: 0, brown: 1 },
  },
  {
    id: 'airplane-cabin',
    name: 'Airplane Cabin',
    category: 'white-noise',
    emoji: '\u2708\uFE0F',
    type: 'feelscape',
    premium: true,
    gradientFrom: '#457b9d',
    gradientTo: '#a8dadc',
    generatorType: 'noise',
    generatorConfig: { lowFreq: 80, highFreq: 600, ampMod: 0.05, ampModFreq: 0.02 },
  },
  {
    id: 'fan',
    name: 'Fan',
    category: 'white-noise',
    emoji: '\uD83C\uDF00',
    type: 'feelscape',
    premium: false,
    gradientFrom: '#adb5bd',
    gradientTo: '#e9ecef',
    generatorType: 'noise',
    generatorConfig: { lowFreq: 100, highFreq: 1500, ampMod: 0.08, ampModFreq: 3 },
  },

  // ── Animals (6) ────────────────────────────────────────────
  {
    id: 'cat-purring',
    name: 'Cat Purring',
    category: 'animals',
    emoji: '\uD83D\uDC31',
    type: 'feelscape',
    premium: false,
    gradientFrom: '#f4a261',
    gradientTo: '#ffd6a5',
    generatorType: 'oscillator',
    generatorConfig: { freq: 26, ampModFreq: 12, waveform: 0 },
  },
  {
    id: 'birds-chirping',
    name: 'Birds Chirping',
    category: 'animals',
    emoji: '\uD83D\uDC26',
    type: 'feelscape',
    premium: false,
    gradientFrom: '#a7c957',
    gradientTo: '#d4e09b',
    generatorType: 'combined',
    generatorConfig: { lowFreq: 2000, highFreq: 4000, chirpRate: 2.5, chirpDuration: 0.12 },
  },
  {
    id: 'cricket-night',
    name: 'Cricket Night',
    category: 'animals',
    emoji: '\uD83E\uDE97',
    type: 'feelscape',
    premium: false,
    gradientFrom: '#1b4332',
    gradientTo: '#40916c',
    generatorType: 'oscillator',
    generatorConfig: { freq: 4500, onDuration: 0.04, offDuration: 0.04, burstGap: 0.8 },
  },
  {
    id: 'whale-song',
    name: 'Whale Song',
    category: 'animals',
    emoji: '\uD83D\uDC33',
    type: 'feelscape',
    premium: true,
    gradientFrom: '#023e8a',
    gradientTo: '#0096c7',
    generatorType: 'oscillator',
    generatorConfig: { freq: 200, freqSweep: 400, sweepDuration: 4, waveform: 0 },
  },
  {
    id: 'horse-galloping',
    name: 'Horse Galloping',
    category: 'animals',
    emoji: '\uD83D\uDC0E',
    type: 'feelscape',
    premium: true,
    gradientFrom: '#bc6c25',
    gradientTo: '#dda15e',
    generatorType: 'combined',
    generatorConfig: { lowFreq: 80, highFreq: 2000, crackleRate: 6, crackleDecay: 0.02 },
  },
  {
    id: 'frogs',
    name: 'Frogs',
    category: 'animals',
    emoji: '\uD83D\uDC38',
    type: 'feelscape',
    premium: false,
    gradientFrom: '#588157',
    gradientTo: '#a3b18a',
    generatorType: 'combined',
    generatorConfig: { lowFreq: 400, highFreq: 1200, chirpRate: 1.5, chirpDuration: 0.3 },
  },

  // ── Music (5) ──────────────────────────────────────────────
  {
    id: 'lullaby',
    name: 'Lullaby',
    category: 'music',
    emoji: '\uD83C\uDF19',
    type: 'feelscape',
    premium: false,
    gradientFrom: '#7b2cbf',
    gradientTo: '#c77dff',
    generatorType: 'oscillator',
    generatorConfig: { melody: 1, tempo: 72, waveform: 0 },
  },
  {
    id: 'meditation-bells',
    name: 'Meditation Bells',
    category: 'music',
    emoji: '\uD83D\uDD14',
    type: 'feelscape',
    premium: false,
    gradientFrom: '#ffd166',
    gradientTo: '#ffe5a0',
    generatorType: 'oscillator',
    generatorConfig: { freq: 880, bellInterval: 6, bellDecay: 3, waveform: 0 },
  },
  {
    id: 'piano-gentle',
    name: 'Piano Gentle',
    category: 'music',
    emoji: '\uD83C\uDFB9',
    type: 'feelscape',
    premium: true,
    gradientFrom: '#264653',
    gradientTo: '#2a9d8f',
    generatorType: 'oscillator',
    generatorConfig: { melody: 2, tempo: 60, waveform: 1 },
  },
  {
    id: 'music-box',
    name: 'Music Box',
    category: 'music',
    emoji: '\uD83C\uDFB6',
    type: 'feelscape',
    premium: false,
    gradientFrom: '#e0aaff',
    gradientTo: '#f0dbff',
    generatorType: 'oscillator',
    generatorConfig: { melody: 3, tempo: 100, waveform: 0 },
  },
  {
    id: 'singing-bowl',
    name: 'Singing Bowl',
    category: 'music',
    emoji: '\uD83E\uDE94',
    type: 'feelscape',
    premium: true,
    gradientFrom: '#d4a373',
    gradientTo: '#faedcd',
    generatorType: 'oscillator',
    generatorConfig: { freq: 528, bellInterval: 8, bellDecay: 5, waveform: 0 },
  },

  // ── Ambience (6) ───────────────────────────────────────────
  {
    id: 'countryside',
    name: 'Countryside',
    category: 'ambience',
    emoji: '\uD83C\uDF3E',
    type: 'feelscape',
    premium: false,
    gradientFrom: '#606c38',
    gradientTo: '#fefae0',
    generatorType: 'combined',
    generatorConfig: { lowFreq: 200, highFreq: 3000, ampMod: 0.15, ampModFreq: 0.1, chirpRate: 1 },
  },
  {
    id: 'forest',
    name: 'Forest',
    category: 'ambience',
    emoji: '\uD83C\uDF32',
    type: 'feelscape',
    premium: false,
    gradientFrom: '#1b4332',
    gradientTo: '#95d5b2',
    generatorType: 'combined',
    generatorConfig: { lowFreq: 150, highFreq: 2000, ampMod: 0.2, ampModFreq: 0.08, chirpRate: 0.8 },
  },
  {
    id: 'beach',
    name: 'Beach',
    category: 'ambience',
    emoji: '\uD83C\uDFD6\uFE0F',
    type: 'feelscape',
    premium: false,
    gradientFrom: '#f77f00',
    gradientTo: '#fcbf49',
    generatorType: 'noise',
    generatorConfig: { lowFreq: 150, highFreq: 1500, ampMod: 0.7, ampModFreq: 0.1 },
  },
  {
    id: 'rainy-cafe',
    name: 'Rainy Caf\u00E9',
    category: 'ambience',
    emoji: '\u2615',
    type: 'feelscape',
    premium: true,
    gradientFrom: '#6c584c',
    gradientTo: '#adc178',
    generatorType: 'combined',
    generatorConfig: { lowFreq: 600, highFreq: 2500, ampMod: 0.2, ampModFreq: 0.2, crackleRate: 0.5 },
  },
  {
    id: 'library',
    name: 'Library',
    category: 'ambience',
    emoji: '\uD83D\uDCDA',
    type: 'feelscape',
    premium: true,
    gradientFrom: '#774936',
    gradientTo: '#c9ada7',
    generatorType: 'noise',
    generatorConfig: { lowFreq: 50, highFreq: 400, ampMod: 0.05, ampModFreq: 0.01 },
  },
  {
    id: 'fireplace',
    name: 'Fireplace',
    category: 'ambience',
    emoji: '\uD83E\uDE94',
    type: 'feelscape',
    premium: false,
    gradientFrom: '#d62828',
    gradientTo: '#f77f00',
    generatorType: 'combined',
    generatorConfig: { lowFreq: 400, highFreq: 4000, crackleRate: 10, crackleDecay: 0.04 },
  },

  // ── Haptics Only (5) ───────────────────────────────────────
  {
    id: 'heartbeat',
    name: 'Heartbeat',
    category: 'haptics',
    emoji: '\uD83D\uDC93',
    type: 'haptic',
    premium: false,
    gradientFrom: '#e63946',
    gradientTo: '#f4a0a8',
    generatorType: 'haptic-only',
    generatorConfig: { pattern: 1, interval: 800 },
  },
  {
    id: 'water-drops',
    name: 'Water Drops',
    category: 'haptics',
    emoji: '\uD83D\uDCA7',
    type: 'haptic',
    premium: false,
    gradientFrom: '#00b4d8',
    gradientTo: '#90e0ef',
    generatorType: 'haptic-only',
    generatorConfig: { pattern: 2, interval: 1200 },
  },
  {
    id: 'shooting-star',
    name: 'Shooting Star',
    category: 'haptics',
    emoji: '\uD83C\uDF20',
    type: 'haptic',
    premium: true,
    gradientFrom: '#3a0ca3',
    gradientTo: '#7209b7',
    generatorType: 'haptic-only',
    generatorConfig: { pattern: 3, interval: 2000 },
  },
  {
    id: 'infinite-pulse',
    name: 'Infinite Pulse',
    category: 'haptics',
    emoji: '\uD83D\uDD1E',
    type: 'haptic',
    premium: false,
    gradientFrom: '#560bad',
    gradientTo: '#b5179e',
    generatorType: 'haptic-only',
    generatorConfig: { pattern: 4, interval: 600 },
  },
  {
    id: 'gentle-wave',
    name: 'Gentle Wave',
    category: 'haptics',
    emoji: '\uD83C\uDF0A',
    type: 'haptic',
    premium: false,
    gradientFrom: '#48bfe3',
    gradientTo: '#5390d9',
    generatorType: 'haptic-only',
    generatorConfig: { pattern: 5, interval: 1500 },
  },
];

export const SLEEP_TIMER_OPTIONS = [
  { label: '5 min', minutes: 5 },
  { label: '10 min', minutes: 10 },
  { label: '15 min', minutes: 15 },
  { label: '30 min', minutes: 30 },
];
