// Copyright (c) 2024-2026 Aminy LLC. All Rights Reserved.
// CONFIDENTIAL AND PROPRIETARY — Trade Secret of Aminy LLC
// Unauthorized use, reproduction, or distribution is strictly prohibited.
// See LICENSE file for details.

/**
 * Reports Hook
 * Manages report generation and storage with real PDF output
 */

import { useState, useCallback } from 'react';
import jsPDF from 'jspdf';

// ============================================================================
// Types
// ============================================================================

export interface Report {
  id: string;
  type: ReportType;
  title: string;
  createdAt: Date;
  status: 'pending' | 'generating' | 'ready' | 'error';
  url?: string;
  blob?: Blob;
  childName?: string;
  reportType?: string;
  reportId?: string;
  expiresAt?: string;
  generatedAt?: string;
}

export type ReportType =
  | 'weekly-outcomes'
  | 'monthly-progress'
  | 'provider-packet'
  | 'iep-summary'
  | 'bcba-notes'
  | 'insurance-letter'
  | 'parent'
  | 'iep'
  | 'bcba';

export interface ReportOptions {
  dateRange?: { start: Date; end: Date };
  includeCharts?: boolean;
  includeNotes?: boolean;
  childName?: string;
  parentName?: string;
  customData?: Record<string, unknown>;
}

// ============================================================================
// PDF Generation Utilities
// ============================================================================

const AMINY_BLUE = '#0891b2';
const AMINY_GREEN = '#4E93A8';
const GRAY_600 = '#4B5563';
const GRAY_400 = '#9CA3AF';

function getReportTitle(type: ReportType): string {
  const titles: Partial<Record<ReportType, string>> = {
    'weekly-outcomes': 'Weekly Outcomes Report',
    'monthly-progress': 'Monthly Progress Summary',
    'provider-packet': 'Provider Referral Packet',
    'iep-summary': 'IEP Progress Report',
    'bcba-notes': 'BCBA Clinical Notes',
    'insurance-letter': 'Insurance Documentation',
    'parent': 'Parent Report',
    'iep': 'IEP Report',
    'bcba': 'BCBA Report',
  };
  return titles[type] || 'Progress Report';
}

function generateBasePDF(
  type: ReportType,
  options: ReportOptions
): jsPDF {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let yPos = margin;

  const title = getReportTitle(type);
  const childName = options.childName || 'Child';
  const parentName = options.parentName || 'Parent';
  const dateRange = options.dateRange || {
    start: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    end: new Date(),
  };

  const formatDate = (date: Date) =>
    date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

  // Header
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(AMINY_BLUE);
  doc.text('Aminy', margin, yPos);
  yPos += 8;

  doc.setFontSize(16);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(GRAY_600);
  doc.text(title, margin, yPos);
  yPos += 10;

  // Period and info
  doc.setFontSize(11);
  doc.setTextColor(GRAY_400);
  doc.text(`${formatDate(dateRange.start)} - ${formatDate(dateRange.end)}`, margin, yPos);
  yPos += 6;
  doc.text(`Child: ${childName} | Parent: ${parentName}`, margin, yPos);
  yPos += 12;

  // Watermark
  doc.setFillColor(245, 245, 245);
  doc.roundedRect(margin, yPos, pageWidth - margin * 2, 10, 2, 2, 'F');
  doc.setFontSize(8);
  doc.setTextColor(GRAY_400);
  doc.text(
    `Generated by Aminy on ${new Date().toLocaleDateString()} | Expires in 7 days`,
    margin + 5,
    yPos + 6
  );
  yPos += 18;

  // Content section header
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(AMINY_BLUE);
  doc.text('Summary', margin, yPos);
  yPos += 10;

  // Placeholder content - in production this would use real data
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(GRAY_600);

  const content = getReportContent(type, childName);
  const lines = doc.splitTextToSize(content, pageWidth - margin * 2);
  doc.text(lines, margin, yPos);
  yPos += lines.length * 5 + 10;

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setDrawColor(GRAY_400);
  doc.line(margin, pageHeight - 25, pageWidth - margin, pageHeight - 25);

  doc.setFontSize(9);
  doc.setTextColor(GRAY_400);
  doc.text(
    'This report is for informational purposes only. Share with your care team.',
    margin,
    pageHeight - 18
  );
  doc.text(
    'Generated by Aminy AI | support@aminy.ai | www.aminy.ai',
    margin,
    pageHeight - 12
  );

  return doc;
}

function getReportContent(type: ReportType, childName: string): string {
  const contents: Record<string, string> = {
    'weekly-outcomes': `This week's progress for ${childName}:\n\n• Completed 12 of 15 planned activities (80% completion)\n• Routine adherence improved to 85%\n• Achieved 3 goals, with 5 more in progress\n• Parent stress level decreased from 5.1 to 4.2\n\nKey Wins:\n• Morning routine completed independently 3 days in a row\n• Used calm-down strategies during frustration\n• Made eye contact with new friend at school\n\nAreas to Focus:\n• Evening transitions remain challenging\n• Homework focus decreased mid-week`,

    'monthly-progress': `Monthly progress summary for ${childName}:\n\n• 85% of weekly activities completed on average\n• 12 goals achieved this month\n• Communication skills showed 15% improvement\n• Social interactions increased by 20%\n\nMilestones Reached:\n• Independently completed morning routine\n• First playdate without support needed\n• Expressed emotions using feeling words`,

    'provider-packet': `Provider referral packet for ${childName}:\n\nPrimary Concerns:\n• Transition difficulties\n• Sensory sensitivities\n• Social communication challenges\n\nParent Goals:\n• Reduce meltdown frequency\n• Develop transition strategies\n• Build peer relationships\n\nCurrent Interventions:\n• Visual schedules\n• Sensory breaks\n• Social stories`,

    'iep-summary': `IEP Progress Report for ${childName}:\n\nGoal 1: Communication\nBaseline: 2-word phrases\nCurrent: 4-5 word sentences\nProgress: On track\n\nGoal 2: Self-Regulation\nBaseline: Required adult intervention\nCurrent: Uses strategies with prompting\nProgress: Making progress\n\nGoal 3: Social Skills\nBaseline: Parallel play only\nCurrent: Initiating peer interactions\nProgress: On track`,

    'bcba-notes': `BCBA Clinical Notes for ${childName}:\n\nSession Date: ${new Date().toLocaleDateString()}\n\nBehavioral Observations:\n• Appropriate engagement during structured activities\n• Decreased verbal protests during transitions\n• Increased use of communication device\n\nInterventions Applied:\n• Visual countdown timer\n• First-Then board\n• Token reinforcement system\n\nRecommendations:\n• Continue current intervention strategies\n• Fade verbal prompts for routine completion\n• Increase peer interaction opportunities`,

    'insurance-letter': `Insurance Documentation for ${childName}:\n\nMedical Necessity Statement:\n\nThis child requires ongoing therapeutic intervention to address developmental delays and behavioral challenges. Current diagnosis supports the need for:\n\n• Applied Behavior Analysis (ABA) services\n• Speech-language therapy\n• Occupational therapy\n\nProgress and Outcomes:\n• Documented improvement in target behaviors\n• Measurable progress toward treatment goals\n• Parent engagement in home programming\n\nContinued services are medically necessary to maintain gains and achieve developmental milestones.`,

    'parent': `Parent report for ${childName}:\n\nThis report summarizes observations and progress from the parent perspective.\n\n• Daily routine compliance and challenges\n• Behavioral patterns noted at home\n• Strategies that have been effective`,

    'iep': `IEP report for ${childName}:\n\nSummary of IEP goal progress and accommodations review.`,

    'bcba': `BCBA report for ${childName}:\n\nBehavioral assessment summary and treatment recommendations.`,
  };

  return contents[type] || `Progress report for ${childName}`;
}

// ============================================================================
// Hook
// ============================================================================

export function useReports(_options?: { accessToken?: string }) {
  const [reports, setReports] = useState<Report[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const generateReport = useCallback(
    async (type: ReportType, options?: ReportOptions): Promise<Report> => {
      setIsGenerating(true);
      setError(null);

      try {
        // Generate the PDF
        const doc = generateBasePDF(type, options || {});
        const blob = doc.output('blob');
        const url = URL.createObjectURL(blob);

        const newReport: Report = {
          id: `report_${Date.now()}`,
          type,
          title: getReportTitle(type),
          createdAt: new Date(),
          status: 'ready',
          url,
          blob,
          childName: options?.childName,
        };

        setReports((prev) => [...prev, newReport]);
        return newReport;
      } catch (err) {
        const errorMessage = err instanceof Error ? err.message : 'Failed to generate report';
        setError(errorMessage);
        throw err;
      } finally {
        setIsGenerating(false);
      }
    },
    []
  );

  const deleteReport = useCallback((id: string) => {
    setReports((prev) => {
      const report = prev.find((r) => r.id === id);
      if (report?.url) {
        URL.revokeObjectURL(report.url);
      }
      return prev.filter((r) => r.id !== id);
    });
  }, []);

  const downloadReport = useCallback(
    (id: string, filename?: string) => {
      const report = reports.find((r) => r.id === id);
      if (report?.blob) {
        const url = URL.createObjectURL(report.blob);
        const link = document.createElement('a');
        link.href = url;
        link.download =
          filename ||
          `aminy-${report.type}-${report.childName?.replace(/\s+/g, '-').toLowerCase() || 'report'}-${new Date().toISOString().split('T')[0]}.pdf`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
      } else if (report?.url) {
        window.open(report.url, '_blank');
      }
    },
    [reports]
  );

  const getReportsByType = useCallback(
    (type: ReportType) => {
      return reports.filter((r) => r.type === type);
    },
    [reports]
  );

  const clearReports = useCallback(() => {
    reports.forEach((report) => {
      if (report.url) {
        URL.revokeObjectURL(report.url);
      }
    });
    setReports([]);
  }, [reports]);

  // Aliases for backward compatibility
  const currentReport = reports.length > 0 ? reports[reports.length - 1] : null;
  const loading = isGenerating;
  const createReport = generateReport;
  const fetchReports = (_childId?: string) => { /* no-op, reports loaded from state */ };
  const removeReport = deleteReport;
  const shareReportWithProvider = async (_reportId: string, _email: string, _message?: string) => { /* no-op placeholder */ };

  return {
    reports,
    isGenerating,
    error,
    generateReport,
    deleteReport,
    downloadReport,
    getReportsByType,
    clearReports,
    // Additional aliases used by ReportsHub
    currentReport,
    loading,
    createReport,
    fetchReports,
    removeReport,
    shareReportWithProvider,
  };
}
