// Copyright (c) 2024-2026 Aminy LLC. All Rights Reserved.
// CONFIDENTIAL AND PROPRIETARY — Trade Secret of Aminy LLC
// Unauthorized use, reproduction, or distribution is strictly prohibited.
// See LICENSE file for details.

/**
 * Share With Provider Button
 * Generates and shares a PDF report with healthcare providers
 * Key differentiator: Aminy enables seamless care team collaboration
 */

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import {
  FileText,
  Share2,
  Download,
  Mail,
  Clipboard,
  Check,
  Loader2,
  X,
  Stethoscope,
  User,
  Building2,
  Link,
} from 'lucide-react';
import { Card } from './ui/card';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Badge } from './ui/badge';
import { toast } from 'sonner';
import { supabase } from '../utils/supabase/client';
import { projectId, publicAnonKey } from '../utils/supabase/info';

interface ProgressReport {
  childName: string;
  parentName: string;
  dateRange: { start: Date; end: Date };
  metrics: {
    stressLevel: { current: number; change: number };
    routineAdherence: { current: number; change: number };
    goalsCompleted: number;
    totalSessions: number;
  };
  highlights: string[];
  concerns: string[];
  recommendations: string[];
}

interface ShareWithProviderButtonProps {
  report: ProgressReport;
  variant?: 'default' | 'compact' | 'inline';
  onShare?: (method: 'download' | 'email' | 'link', recipient?: string) => void;
}

export function ShareWithProviderButton({
  report,
  variant = 'default',
  onShare,
}: ShareWithProviderButtonProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [shareMethod, setShareMethod] = useState<'download' | 'email' | 'link' | null>(null);
  const [email, setEmail] = useState('');
  const [linkCopied, setLinkCopied] = useState(false);

  const generatePDF = async (): Promise<Blob | null> => {
    setGenerating(true);

    try {
      // In production, this would call a server endpoint to generate PDF
      // For now, simulate with delay
      await new Promise((r) => setTimeout(r, 1500));

      // Create a simple text representation for demo
      const content = `
AMINY PROGRESS REPORT
=====================

Child: ${report.childName}
Parent: ${report.parentName}
Report Period: ${report.dateRange.start.toLocaleDateString()} - ${report.dateRange.end.toLocaleDateString()}

METRICS SUMMARY
---------------
Parent Stress Level: ${report.metrics.stressLevel.current}/10 (${report.metrics.stressLevel.change > 0 ? '+' : ''}${report.metrics.stressLevel.change} from baseline)
Routine Adherence: ${report.metrics.routineAdherence.current}% (${report.metrics.routineAdherence.change > 0 ? '+' : ''}${report.metrics.routineAdherence.change}%)
Goals Completed: ${report.metrics.goalsCompleted}
Total Sessions: ${report.metrics.totalSessions}

HIGHLIGHTS
----------
${report.highlights.map((h) => `• ${h}`).join('\n')}

AREAS OF CONCERN
----------------
${report.concerns.map((c) => `• ${c}`).join('\n')}

RECOMMENDATIONS
---------------
${report.recommendations.map((r) => `• ${r}`).join('\n')}

---
Generated by Aminy - ${new Date().toLocaleDateString()}
www.aminy.ai
      `.trim();

      // Create blob (in production, this would be actual PDF)
      const blob = new Blob([content], { type: 'text/plain' });
      return blob;
    } catch (error) {
      console.error('Error generating PDF:', error);
      toast.error('Failed to generate report');
      return null;
    } finally {
      setGenerating(false);
    }
  };

  const handleDownload = async () => {
    const blob = await generatePDF();
    if (!blob) return;

    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `aminy-report-${report.childName.toLowerCase().replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);

    toast.success('Report downloaded!');
    onShare?.('download');
    setIsOpen(false);
  };

  const handleEmailShare = async () => {
    if (!email) {
      toast.error('Please enter an email address');
      return;
    }

    setGenerating(true);
    try {
      // Get auth token for the API call
      const { data: { session } } = await supabase.auth.getSession();
      const token = session?.access_token || publicAnonKey;

      const response = await fetch(
        `https://${projectId}.supabase.co/functions/v1/make-server-8a022548/reports/share-direct`,
        {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${token}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            recipientEmail: email,
            childName: report.childName,
            parentName: report.parentName,
            reportSummary: {
              dateRange: {
                start: report.dateRange.start.toISOString(),
                end: report.dateRange.end.toISOString(),
              },
              metrics: report.metrics,
              highlights: report.highlights,
              concerns: report.concerns,
              recommendations: report.recommendations,
            },
          }),
        }
      );

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.error || 'Failed to send email');
      }

      toast.success(`Report sent to ${email}`);
      onShare?.('email', email);
      setIsOpen(false);
      setEmail('');
    } catch (error: unknown) {
      console.error('Email share error:', error);
      toast.error(error instanceof Error ? error.message : 'Failed to send email. Please try again.');
    } finally {
      setGenerating(false);
    }
  };

  const handleCopyLink = async () => {
    setGenerating(true);
    try {
      // In production, generate shareable link via server
      await new Promise((r) => setTimeout(r, 500));

      const link = `https://app.aminy.com/shared/report/${Date.now()}`;
      await navigator.clipboard.writeText(link);

      setLinkCopied(true);
      toast.success('Link copied! Valid for 7 days.');
      onShare?.('link');

      setTimeout(() => setLinkCopied(false), 3000);
    } catch (error) {
      toast.error('Failed to copy link');
    } finally {
      setGenerating(false);
    }
  };

  if (variant === 'inline') {
    return (
      <Button
        variant="outline"
        size="sm"
        onClick={() => setIsOpen(true)}
        className="gap-2"
      >
        <Share2 className="w-4 h-4" />
        Share with Provider
      </Button>
    );
  }

  if (variant === 'compact') {
    return (
      <>
        <button
          onClick={() => setIsOpen(true)}
          className="flex items-center gap-2 text-sm text-[#6B9080] hover:text-[#6B9080]"
        >
          <FileText className="w-4 h-4" />
          Share Report
        </button>

        <ShareModal
          isOpen={isOpen}
          onClose={() => setIsOpen(false)}
          report={report}
          generating={generating}
          shareMethod={shareMethod}
          setShareMethod={setShareMethod}
          email={email}
          setEmail={setEmail}
          linkCopied={linkCopied}
          onDownload={handleDownload}
          onEmail={handleEmailShare}
          onCopyLink={handleCopyLink}
        />
      </>
    );
  }

  return (
    <>
      <Card className="p-4 bg-gradient-to-r from-[#F6FBFB] to-[#F5F2EC] border-[#C8DDE8]">
        <div className="flex items-start gap-3 sm:gap-4">
          <div className="p-2 bg-blue-100 rounded-full">
            <Stethoscope className="w-5 h-5 text-blue-600" />
          </div>
          <div className="flex-1">
            <h3 className="font-medium text-blue-900">Share with Your Care Team</h3>
            <p className="text-sm text-blue-700 mt-1">
              Generate a provider-ready report to share with your BCBA, therapist, or doctor.
            </p>
            <Badge className="mt-2 bg-[#6B9080]/10 text-[#6B9080]">
              Only with Aminy
            </Badge>
          </div>
          <Button onClick={() => setIsOpen(true)} className="bg-blue-600 hover:bg-blue-700">
            <Share2 className="w-4 h-4 mr-2" />
            Share Report
          </Button>
        </div>
      </Card>

      <ShareModal
        isOpen={isOpen}
        onClose={() => setIsOpen(false)}
        report={report}
        generating={generating}
        shareMethod={shareMethod}
        setShareMethod={setShareMethod}
        email={email}
        setEmail={setEmail}
        linkCopied={linkCopied}
        onDownload={handleDownload}
        onEmail={handleEmailShare}
        onCopyLink={handleCopyLink}
      />
    </>
  );
}

interface ShareModalProps {
  isOpen: boolean;
  onClose: () => void;
  report: ProgressReport;
  generating: boolean;
  shareMethod: 'download' | 'email' | 'link' | null;
  setShareMethod: (method: 'download' | 'email' | 'link' | null) => void;
  email: string;
  setEmail: (email: string) => void;
  linkCopied: boolean;
  onDownload: () => void;
  onEmail: () => void;
  onCopyLink: () => void;
}

function ShareModal({
  isOpen,
  onClose,
  report,
  generating,
  shareMethod,
  setShareMethod,
  email,
  setEmail,
  linkCopied,
  onDownload,
  onEmail,
  onCopyLink,
}: ShareModalProps) {
  if (!isOpen) return null;

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50"
        onClick={onClose}
      >
        <motion.div
          initial={{ scale: 0.95, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          exit={{ scale: 0.95, opacity: 0 }}
          className="w-full max-w-md"
          onClick={(e) => e.stopPropagation()}
        >
          <Card className="overflow-hidden">
            {/* Header */}
            <div className="p-4 bg-gradient-to-r from-blue-600 to-teal-600 text-white">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <FileText className="w-5 h-5" />
                  <span className="font-semibold">Share Progress Report</span>
                </div>
                <button onClick={onClose} className="p-1 min-h-[44px] min-w-[44px] flex items-center justify-center hover:bg-white/20 rounded-full">
                  <X className="w-5 h-5" />
                </button>
              </div>
            </div>

            {/* Report Preview */}
            <div className="p-4 bg-[#F6FBFB] border-b">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-10 h-10 bg-[#6B9080]/10 rounded-full flex items-center justify-center">
                  <User className="w-5 h-5 text-[#6B9080]" />
                </div>
                <div>
                  <p className="font-medium text-[#132F43]">{report.childName}'s Progress Report</p>
                  <p className="text-sm text-[#5A6B7A]">
                    {report.dateRange.start.toLocaleDateString()} - {report.dateRange.end.toLocaleDateString()}
                  </p>
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-sm">
                <div className="p-2 bg-white rounded border">
                  <span className="text-[#5A6B7A]">Stress Level</span>
                  <p className="font-medium text-[#132F43]">
                    {report.metrics.stressLevel.current}/10
                  </p>
                </div>
                <div className="p-2 bg-white rounded border">
                  <span className="text-[#5A6B7A]">Routine Adherence</span>
                  <p className="font-medium text-[#132F43]">
                    {report.metrics.routineAdherence.current}%
                  </p>
                </div>
              </div>
            </div>

            {/* Share Options */}
            <div className="p-4 space-y-3">
              <p className="text-sm text-[#5A6B7A] mb-4">
                Choose how you'd like to share this report:
              </p>

              {/* Download Option */}
              <button
                onClick={() => {
                  setShareMethod('download');
                  onDownload();
                }}
                disabled={generating}
                className="w-full flex items-center gap-3 sm:gap-4 p-3 border rounded-lg hover:bg-[#F6FBFB] transition-colors text-left"
              >
                <div className="w-10 h-10 bg-green-100 rounded-full flex items-center justify-center">
                  <Download className="w-5 h-5 text-green-600" />
                </div>
                <div className="flex-1">
                  <p className="font-medium text-[#132F43]">Download PDF</p>
                  <p className="text-sm text-[#5A6B7A]">Save to your device</p>
                </div>
                {generating && shareMethod === 'download' && (
                  <Loader2 className="w-5 h-5 animate-spin text-[#8A9BA8]" />
                )}
              </button>

              {/* Email Option */}
              <div className="border rounded-lg p-3">
                <button
                  onClick={() => setShareMethod(shareMethod === 'email' ? null : 'email')}
                  className="w-full flex items-center gap-3 sm:gap-4 text-left"
                >
                  <div className="w-10 h-10 bg-blue-100 rounded-full flex items-center justify-center">
                    <Mail className="w-5 h-5 text-blue-600" />
                  </div>
                  <div className="flex-1">
                    <p className="font-medium text-[#132F43]">Email to Provider</p>
                    <p className="text-sm text-[#5A6B7A]">Send directly via email</p>
                  </div>
                </button>

                {shareMethod === 'email' && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: 'auto', opacity: 1 }}
                    className="mt-3 pt-3 border-t"
                  >
                    <div className="flex gap-2">
                      <Input
                        type="email"
                        placeholder="provider@clinic.com"
                        value={email}
                        onChange={(e) => setEmail(e.target.value)}
                        className="flex-1"
                      />
                      <Button onClick={onEmail} disabled={generating || !email}>
                        {generating ? (
                          <Loader2 className="w-4 h-4 animate-spin" />
                        ) : (
                          'Send'
                        )}
                      </Button>
                    </div>
                  </motion.div>
                )}
              </div>

              {/* Copy Link Option */}
              <button
                onClick={onCopyLink}
                disabled={generating}
                className="w-full flex items-center gap-3 sm:gap-4 p-3 border rounded-lg hover:bg-[#F6FBFB] transition-colors text-left"
              >
                <div className="w-10 h-10 bg-purple-100 rounded-full flex items-center justify-center">
                  {linkCopied ? (
                    <Check className="w-5 h-5 text-purple-600" />
                  ) : (
                    <Link className="w-5 h-5 text-purple-600" />
                  )}
                </div>
                <div className="flex-1">
                  <p className="font-medium text-[#132F43]">
                    {linkCopied ? 'Link Copied!' : 'Copy Shareable Link'}
                  </p>
                  <p className="text-sm text-[#5A6B7A]">Valid for 7 days, view-only access</p>
                </div>
                {generating && shareMethod === 'link' && (
                  <Loader2 className="w-5 h-5 animate-spin text-[#8A9BA8]" />
                )}
              </button>
            </div>

            {/* Privacy Note */}
            <div className="px-4 pb-4">
              <p className="text-sm text-[#5A6B7A] text-center">
                Reports are encrypted and HIPAA-conscious. You control who sees your data.
              </p>
            </div>
          </Card>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}

export default ShareWithProviderButton;
