/**
 * WeeklyAISummary - AI-generated weekly insights and summaries
 *
 * Features:
 * - Weekly progress summary generated by AI
 * - Key insights and observations
 * - Trend detection
 * - Recommendations for the coming week
 * - Shareable summary card
 */

import React, { useState, useEffect } from 'react';
import { motion } from 'motion/react';
import {
  Sparkles,
  TrendingUp,
  TrendingDown,
  Minus,
  Calendar,
  Target,
  Lightbulb,
  ArrowRight,
  Share2,
  Download,
  ChevronRight,
  Loader2,
  RefreshCw,
  Award,
  Heart,
  AlertCircle,
  CheckCircle2,
  Star
} from 'lucide-react';
import { Card } from './ui/card';
import { Button } from './ui/button';
import { Badge } from './ui/badge';
import { Progress } from './ui/progress';
import { toast } from 'sonner';
import { supabase } from '../utils/supabase/client';
import { projectId, publicAnonKey } from '../utils/supabase/info';
import { generateCaregiverSummary, getLatestCaregiverSummary } from '../lib/caregiver-workflow';

interface WeeklySummary {
  weekOf: string;
  overallProgress: number;
  progressTrend: 'up' | 'down' | 'stable';
  highlights: string[];
  challenges: string[];
  recommendations: string[];
  goalsProgress: {
    name: string;
    progress: number;
    trend: 'up' | 'down' | 'stable';
  }[];
  moodPattern: 'positive' | 'neutral' | 'challenging';
  streakDays: number;
  activitiesCompleted: number;
  conversationsCount: number;
}

interface BehaviorLogRow {
  behavior_type: string | null;
  intensity: number | null;
  trigger: string | null;
  is_positive: boolean;
  logged_at: string | null;
  notes: string | null;
}

interface RoutineCompletionRow {
  routine_id: string;
  completion_status: string;
  scheduled_date: string;
  completed_steps: number | null;
  total_steps: number | null;
}

interface GoalRow {
  id: string;
  title: string | null;
  area: string | null;
  progress: number | null;
  completed: boolean;
  target_date: string | null;
}

interface ConversationRow {
  id: string;
  created_at: string;
  topic: string | null;
}

interface InsightRow {
  content: string;
  created_at: string;
}

interface CachedSummaryRow {
  summary_data: WeeklySummary;
  [key: string]: unknown;
}

interface WeeklyAISummaryProps {
  childName: string;
  childId?: string;
  onViewDetails?: () => void;
  compact?: boolean;
}

export function WeeklyAISummary({
  childName,
  childId,
  onViewDetails,
  compact = false
}: WeeklyAISummaryProps) {
  const [isLoading, setIsLoading] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);
  const [summary, setSummary] = useState<WeeklySummary | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    loadWeeklySummary();
  }, [childId]);

  const loadWeeklySummary = async () => {
    setIsLoading(true);
    setError(null);

    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;

      const latestSummary = await getLatestCaregiverSummary({
        userId: user.id,
        childId,
        periodStart: getWeekStart(),
      });

      if (latestSummary?.snapshot?.weeklySummary) {
        setSummary(latestSummary.snapshot.weeklySummary);
      } else {
        setSummary(null);
      }
    } catch (err) {
      console.error('Error loading summary:', err);
      setSummary(null);
    } finally {
      setIsLoading(false);
    }
  };

  /**
   * Fetch the past 7 days of user data from Supabase for the AI to analyze.
   */
  const fetchWeeklyData = async (userId: string) => {
    const weekAgo = new Date();
    weekAgo.setDate(weekAgo.getDate() - 7);
    const weekAgoISO = weekAgo.toISOString();
    const weekAgoDate = weekAgoISO.split('T')[0];

    // Fetch all relevant data in parallel
    const [
      behaviorRes,
      routineRes,
      goalsRes,
      conversationRes,
      streakRes,
      insightsRes,
    ] = await Promise.all([
      supabase
        .from('behavior_logs')
        .select('behavior_type, intensity, trigger, is_positive, logged_at, notes')
        .eq('user_id', userId)
        .gte('logged_at', weekAgoISO)
        .order('logged_at', { ascending: true })
        .limit(200),
      supabase
        .from('routine_completions')
        .select('routine_id, completion_status, scheduled_date, completed_steps, total_steps')
        .eq('user_id', userId)
        .gte('scheduled_date', weekAgoDate)
        .limit(200),
      supabase
        .from('goals')
        .select('id, title, area, progress, completed, target_date')
        .eq('user_id', userId)
        .limit(50),
      supabase
        .from('conversations')
        .select('id, created_at, topic')
        .eq('user_id', userId)
        .gte('created_at', weekAgoISO)
        .limit(100),
      supabase
        .from('user_streaks')
        .select('current_streak')
        .eq('user_id', userId)
        .single(),
      supabase
        .from('ai_insights')
        .select('content, created_at')
        .eq('user_id', userId)
        .gte('created_at', weekAgoISO)
        .order('created_at', { ascending: false })
        .limit(10),
    ]);

    return {
      behaviors: (behaviorRes.data || []) as BehaviorLogRow[],
      routines: (routineRes.data || []) as RoutineCompletionRow[],
      goals: (goalsRes.data || []) as GoalRow[],
      conversations: (conversationRes.data || []) as ConversationRow[],
      streak: (streakRes.data?.current_streak || 0) as number,
      insights: ((insightsRes.data || []) as InsightRow[]).map((i) => i.content),
    };
  };

  /**
   * Call the AI Edge Function with the weekly data to generate a real summary.
   */
  const callAIForSummary = async (
    weeklyData: Awaited<ReturnType<typeof fetchWeeklyData>>
  ): Promise<WeeklySummary> => {
    const systemPrompt = `You are Aminy, an AI wellness companion for neurodivergent families.

You are generating a WEEKLY PROGRESS SUMMARY for a parent about their child "${childName}".

Analyze the data provided and return a JSON object with EXACTLY this structure (no markdown, no code fences, just raw JSON):
{
  "weekOf": "<YYYY-MM-DD of this week's Monday>",
  "overallProgress": <number 0-100>,
  "progressTrend": "<up|down|stable>",
  "highlights": ["<string>", "<string>", "<string>"],
  "challenges": ["<string>", "<string>"],
  "recommendations": ["<string>", "<string>", "<string>"],
  "goalsProgress": [
    {"name": "<goal name>", "progress": <number 0-100>, "trend": "<up|down|stable>"}
  ],
  "moodPattern": "<positive|neutral|challenging>",
  "streakDays": <number>,
  "activitiesCompleted": <number>,
  "conversationsCount": <number>
}

Rules:
- highlights: 2-4 specific positive observations from the data. Reference actual behaviors or routines.
- challenges: 1-3 areas that need attention. Be compassionate, not critical.
- recommendations: 2-4 actionable, specific strategies for the coming week.
- goalsProgress: Map the user's goals to progress entries. If no goals exist, create 2-3 inferred focus areas from the behavior data.
- overallProgress: A holistic score considering routine adherence, positive behaviors, and goal progress.
- progressTrend: Compare this week's data pattern to infer direction.
- moodPattern: Infer from behavior log sentiment (is_positive flags, intensity levels).
- streakDays: Use the provided streak value.
- activitiesCompleted: Count of completed routines + positive behavior entries.
- conversationsCount: Number of AI conversations this week.

Be warm, encouraging, and specific. Use the child's name "${childName}" in highlights and recommendations.`;

    const userMessage = `Here is ${childName}'s data from the past 7 days:

BEHAVIOR LOGS (${weeklyData.behaviors.length} entries):
${weeklyData.behaviors.length > 0
  ? weeklyData.behaviors.map(b =>
      `- ${b.behavior_type || 'behavior'} | intensity: ${b.intensity ?? 'n/a'} | positive: ${b.is_positive ? 'yes' : 'no'} | trigger: ${b.trigger || 'none'} | ${b.logged_at?.split('T')[0] || ''}${b.notes ? ' | notes: ' + b.notes : ''}`
    ).join('\n')
  : 'No behavior logs recorded this week.'}

ROUTINE COMPLETIONS (${weeklyData.routines.length} entries):
${weeklyData.routines.length > 0
  ? weeklyData.routines.map(r =>
      `- routine ${r.routine_id} | status: ${r.completion_status} | steps: ${r.completed_steps ?? '?'}/${r.total_steps ?? '?'} | date: ${r.scheduled_date}`
    ).join('\n')
  : 'No routine completions recorded this week.'}

ACTIVE GOALS (${weeklyData.goals.length}):
${weeklyData.goals.length > 0
  ? weeklyData.goals.map(g =>
      `- ${g.title || g.area || 'Goal'} | area: ${g.area || 'general'} | progress: ${g.progress ?? 0}% | completed: ${g.completed ? 'yes' : 'no'}`
    ).join('\n')
  : 'No goals configured yet.'}

AI CONVERSATIONS THIS WEEK: ${weeklyData.conversations.length}
CURRENT STREAK: ${weeklyData.streak} days

RECENT AI INSIGHTS:
${weeklyData.insights.length > 0 ? weeklyData.insights.join('\n') : 'None yet.'}

Please generate the weekly summary JSON now.`;

    const response = await fetch(
      `https://${projectId}.supabase.co/functions/v1/make-server-8a022548/ai/brain`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${publicAnonKey}`,
        },
        body: JSON.stringify({
          userMessage,
          conversationHistory: [],
          systemPrompt,
        }),
      }
    );

    if (!response.ok) {
      let errorMessage = `Server returned ${response.status}`;
      try {
        const errorData: Record<string, unknown> = await response.json();
        errorMessage = (typeof errorData.error === 'string' ? errorData.error : null) || errorMessage;
      } catch {
        const errorText = await response.text();
        errorMessage = errorText || errorMessage;
      }
      throw new Error(errorMessage);
    }

    const data: Record<string, unknown> = await response.json();
    const aiMessage: string = (data.message as string) || '';

    // Parse the JSON from the AI response — strip markdown fences if present
    const cleaned = aiMessage.replace(/```json\s*/gi, '').replace(/```\s*/g, '').trim();
    const parsed: Record<string, unknown> = JSON.parse(cleaned);

    // Validate and ensure correct shape
    const progressTrendValue = parsed.progressTrend as string;
    const moodPatternValue = parsed.moodPattern as string;

    return {
      weekOf: (typeof parsed.weekOf === 'string' ? parsed.weekOf : getWeekStart()),
      overallProgress: typeof parsed.overallProgress === 'number' ? parsed.overallProgress : 50,
      progressTrend: (['up', 'down', 'stable'].includes(progressTrendValue) ? progressTrendValue : 'stable') as 'up' | 'down' | 'stable',
      highlights: Array.isArray(parsed.highlights) ? (parsed.highlights as string[]) : [],
      challenges: Array.isArray(parsed.challenges) ? (parsed.challenges as string[]) : [],
      recommendations: Array.isArray(parsed.recommendations) ? (parsed.recommendations as string[]) : [],
      goalsProgress: Array.isArray(parsed.goalsProgress)
        ? (parsed.goalsProgress as Record<string, unknown>[]).map((g) => ({
            name: typeof g.name === 'string' ? g.name : 'Goal',
            progress: typeof g.progress === 'number' ? g.progress : 0,
            trend: (['up', 'down', 'stable'].includes(g.trend as string) ? (g.trend as string) : 'stable') as 'up' | 'down' | 'stable',
          }))
        : [],
      moodPattern: (['positive', 'neutral', 'challenging'].includes(moodPatternValue) ? moodPatternValue : 'neutral') as 'positive' | 'neutral' | 'challenging',
      streakDays: typeof parsed.streakDays === 'number' ? parsed.streakDays : 0,
      activitiesCompleted: typeof parsed.activitiesCompleted === 'number' ? parsed.activitiesCompleted : 0,
      conversationsCount: typeof parsed.conversationsCount === 'number' ? parsed.conversationsCount : 0,
    };
  };

  const generateSummary = async () => {
    setIsGenerating(true);
    setError(null);

    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) {
        setError('Please sign in to generate your weekly summary.');
        return;
      }

      const generated = await generateCaregiverSummary({
        userId: user.id,
        childId,
        periodStart: getWeekStart(),
        forceRegenerate: true,
      });

      setSummary(generated.snapshot.weeklySummary);
      toast.success('Weekly insights generated from stored caregiver records.');
    } catch (err) {
      console.error('Error generating summary:', err);
      setError('Failed to generate summary. Please try again.');
      toast.error('Failed to generate summary');
    } finally {
      setIsGenerating(false);
    }
  };

  /**
   * Data-driven fallback when the AI Edge Function is unreachable.
   * Produces a summary derived from the actual Supabase data instead of hardcoded mock values.
   */
  const buildFallbackSummary = (
    weeklyData: Awaited<ReturnType<typeof fetchWeeklyData>>
  ): WeeklySummary => {
    const completedRoutines = weeklyData.routines.filter(
      (r) => r.completion_status === 'completed'
    ).length;
    const totalRoutines = weeklyData.routines.length;
    const adherence = totalRoutines > 0
      ? Math.round((completedRoutines / totalRoutines) * 100)
      : 0;

    const positiveBehaviors = weeklyData.behaviors.filter((b) => b.is_positive).length;
    const challengingBehaviors = weeklyData.behaviors.filter((b) => !b.is_positive).length;

    const overallProgress = Math.min(
      100,
      Math.round(
        (adherence * 0.4) +
        (positiveBehaviors > 0 ? Math.min(positiveBehaviors * 5, 30) : 0) +
        (weeklyData.streak * 3) +
        (weeklyData.conversations.length > 0 ? 10 : 0)
      )
    );

    const progressTrend: 'up' | 'down' | 'stable' =
      positiveBehaviors > challengingBehaviors ? 'up'
      : challengingBehaviors > positiveBehaviors ? 'down'
      : 'stable';

    const moodPattern: 'positive' | 'neutral' | 'challenging' =
      positiveBehaviors > challengingBehaviors * 2 ? 'positive'
      : challengingBehaviors > positiveBehaviors ? 'challenging'
      : 'neutral';

    const highlights: string[] = [];
    if (completedRoutines > 0)
      highlights.push(`${childName} completed ${completedRoutines} routine${completedRoutines > 1 ? 's' : ''} this week`);
    if (positiveBehaviors > 0)
      highlights.push(`${positiveBehaviors} positive behavior${positiveBehaviors > 1 ? 's' : ''} logged`);
    if (weeklyData.streak > 0)
      highlights.push(`${weeklyData.streak}-day app usage streak`);
    if (highlights.length === 0)
      highlights.push('Keep logging to unlock personalized insights!');

    const challenges: string[] = [];
    if (challengingBehaviors > 0) {
      const triggers = weeklyData.behaviors
        .filter((b) => !b.is_positive && b.trigger)
        .map((b) => b.trigger);
      const uniqueTriggers = [...new Set(triggers)].slice(0, 2);
      challenges.push(
        `${challengingBehaviors} challenging behavior${challengingBehaviors > 1 ? 's' : ''} recorded` +
        (uniqueTriggers.length > 0 ? ` (common triggers: ${uniqueTriggers.join(', ')})` : '')
      );
    }
    if (totalRoutines === 0)
      challenges.push('No routines tracked this week — setting up routines can help build consistency');

    const recommendations: string[] = [
      adherence < 50
        ? 'Try to complete at least one routine each day to build momentum'
        : 'Great routine consistency! Consider adding a new routine to stretch skills',
      challengingBehaviors > 0
        ? 'Review the behavior triggers and try a calm-down strategy before those situations'
        : 'Keep up the positive trend — celebrate the wins with your child',
    ];

    const goalsProgress = weeklyData.goals.length > 0
      ? weeklyData.goals.slice(0, 4).map((g) => ({
          name: g.title || g.area || 'Goal',
          progress: g.progress ?? 0,
          trend: (g.completed ? 'up' : 'stable') as 'up' | 'down' | 'stable',
        }))
      : [
          { name: 'Daily Routines', progress: adherence, trend: progressTrend },
          { name: 'Positive Behaviors', progress: Math.min(100, positiveBehaviors * 10), trend: progressTrend },
        ];

    return {
      weekOf: getWeekStart(),
      overallProgress,
      progressTrend,
      highlights,
      challenges,
      recommendations,
      goalsProgress,
      moodPattern,
      streakDays: weeklyData.streak,
      activitiesCompleted: completedRoutines + positiveBehaviors,
      conversationsCount: weeklyData.conversations.length,
    };
  };

  const getWeekStart = (): string => {
    const now = new Date();
    const dayOfWeek = now.getDay();
    const diff = now.getDate() - dayOfWeek + (dayOfWeek === 0 ? -6 : 1);
    const weekStart = new Date(now.setDate(diff));
    return weekStart.toISOString().split('T')[0];
  };

  const parseSummary = (data: CachedSummaryRow): WeeklySummary => {
    return data.summary_data;
  };


  const getTrendIcon = (trend: 'up' | 'down' | 'stable') => {
    switch (trend) {
      case 'up':
        return <TrendingUp className="w-4 h-4 text-green-500" />;
      case 'down':
        return <TrendingDown className="w-4 h-4 text-red-500" />;
      default:
        return <Minus className="w-4 h-4 text-gray-400" />;
    }
  };

  const getMoodColor = (mood: string) => {
    switch (mood) {
      case 'positive':
        return 'bg-green-100 text-green-700 border-green-200';
      case 'challenging':
        return 'bg-amber-100 text-amber-700 border-amber-200';
      default:
        return 'bg-gray-100 text-gray-700 border-gray-200';
    }
  };

  const handleShare = async () => {
    if (!summary) return;

    const shareText = `
${childName}'s Weekly Progress Summary

Overall Progress: ${summary.overallProgress}%

Highlights:
${summary.highlights.map(h => `• ${h}`).join('\n')}

Keep up the great work! 🌟

Generated by Aminy
    `.trim();

    if (navigator.share) {
      try {
        await navigator.share({
          title: `${childName}'s Weekly Progress`,
          text: shareText
        });
      } catch (err) {
        // User cancelled or error
      }
    } else {
      await navigator.clipboard.writeText(shareText);
      toast.success('Summary copied to clipboard!');
    }
  };

  if (isLoading) {
    return (
      <Card className="p-6">
        <div className="flex items-center justify-center">
          <Loader2 className="w-6 h-6 animate-spin text-teal-500" />
          <span className="ml-2 text-muted-foreground">Loading insights...</span>
        </div>
      </Card>
    );
  }

  if (!summary) {
    return (
      <Card className="p-6 text-center">
        <Sparkles className="w-8 h-8 text-muted-foreground mx-auto mb-3" />
        <p className="text-muted-foreground mb-2">No summary available yet</p>
        {error && (
          <p className="text-sm text-red-500 mb-4">{error}</p>
        )}
        <p className="text-xs text-muted-foreground mb-4">
          Generate an AI-powered summary of your child's progress from the past week
        </p>
        <Button onClick={generateSummary} disabled={isGenerating}>
          {isGenerating ? (
            <>
              <Loader2 className="w-4 h-4 mr-2 animate-spin" />
              Analyzing this week's data...
            </>
          ) : (
            <>
              <Sparkles className="w-4 h-4 mr-2" />
              Generate Weekly Summary
            </>
          )}
        </Button>
      </Card>
    );
  }

  // Compact version for dashboard
  if (compact) {
    return (
      <Card className="p-4 hover:shadow-md transition-shadow cursor-pointer" onClick={onViewDetails}>
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-gradient-to-br from-purple-500 to-pink-500 rounded-lg flex items-center justify-center">
              <Sparkles className="w-4 h-4 text-white" />
            </div>
            <div>
              <h3 className="font-semibold text-sm dark:text-white">Weekly Insights</h3>
              <p className="text-xs text-muted-foreground">Week of {new Date(summary.weekOf).toLocaleDateString()}</p>
            </div>
          </div>
          <div className="flex items-center gap-1">
            <span className="text-lg font-bold text-teal-600">{summary.overallProgress}%</span>
            {getTrendIcon(summary.progressTrend)}
          </div>
        </div>

        <div className="space-y-2">
          <div className="flex items-center gap-2 text-sm">
            <CheckCircle2 className="w-4 h-4 text-green-500 flex-shrink-0" />
            <span className="text-gray-600 dark:text-gray-300 truncate">{summary.highlights[0]}</span>
          </div>
          {summary.recommendations[0] && (
            <div className="flex items-center gap-2 text-sm">
              <Lightbulb className="w-4 h-4 text-amber-500 flex-shrink-0" />
              <span className="text-gray-600 dark:text-gray-300 truncate">{summary.recommendations[0]}</span>
            </div>
          )}
        </div>

        <div className="flex items-center justify-between mt-3 pt-3 border-t border-gray-100 dark:border-slate-700">
          <div className="flex gap-3">
            <Badge variant="outline" className="text-xs">
              <Star className="w-3 h-3 mr-1" />
              {summary.streakDays} day streak
            </Badge>
            <Badge variant="outline" className={`text-xs ${getMoodColor(summary.moodPattern)}`}>
              {summary.moodPattern}
            </Badge>
          </div>
          <ChevronRight className="w-4 h-4 text-muted-foreground" />
        </div>
      </Card>
    );
  }

  // Full version
  return (
    <div className="space-y-6">
      {/* Header */}
      <Card className="p-6 bg-gradient-to-br from-purple-50 to-pink-50 dark:from-purple-900/20 dark:to-pink-900/20 border-purple-200 dark:border-purple-800">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 bg-gradient-to-br from-purple-500 to-pink-500 rounded-xl flex items-center justify-center">
              <Sparkles className="w-6 h-6 text-white" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-xl font-semibold dark:text-white">Weekly Insights</h2>
                <Badge variant="outline" className="text-xs bg-amber-50 text-amber-700 border-amber-300">Preview</Badge>
              </div>
              <p className="text-sm text-muted-foreground">
                Week of {new Date(summary.weekOf).toLocaleDateString('en-US', { month: 'long', day: 'numeric' })}
              </p>
            </div>
          </div>

          <div className="flex gap-2">
            <Button variant="outline" size="sm" onClick={handleShare}>
              <Share2 className="w-4 h-4 mr-1" />
              Share
            </Button>
            <Button variant="outline" size="sm" onClick={generateSummary} disabled={isGenerating}>
              {isGenerating ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <RefreshCw className="w-4 h-4" />
              )}
            </Button>
          </div>
        </div>

        {/* Overall Progress */}
        <div className="flex items-center gap-4">
          <div className="flex-1">
            <div className="flex items-center justify-between mb-2">
              <span className="text-sm font-medium text-gray-700 dark:text-gray-300">Overall Progress</span>
              <div className="flex items-center gap-1">
                <span className="text-2xl font-bold text-purple-600 dark:text-purple-400">{summary.overallProgress}%</span>
                {getTrendIcon(summary.progressTrend)}
              </div>
            </div>
            <Progress value={summary.overallProgress} className="h-3" />
          </div>
        </div>

        {/* Quick Stats */}
        <div className="grid grid-cols-3 gap-4 mt-4 pt-4 border-t border-purple-200 dark:border-purple-700">
          <div className="text-center">
            <p className="text-2xl font-bold text-purple-600 dark:text-purple-400">{summary.streakDays}</p>
            <p className="text-xs text-muted-foreground">Day Streak</p>
          </div>
          <div className="text-center">
            <p className="text-2xl font-bold text-purple-600 dark:text-purple-400">{summary.activitiesCompleted}</p>
            <p className="text-xs text-muted-foreground">Activities</p>
          </div>
          <div className="text-center">
            <p className="text-2xl font-bold text-purple-600 dark:text-purple-400">{summary.conversationsCount}</p>
            <p className="text-xs text-muted-foreground">AI Chats</p>
          </div>
        </div>
      </Card>

      {/* Goals Progress */}
      <Card className="p-6">
        <h3 className="font-semibold mb-4 flex items-center gap-2 dark:text-white">
          <Target className="w-5 h-5 text-teal-500" />
          Goals Progress
        </h3>
        <div className="space-y-4">
          {summary.goalsProgress.map((goal, index) => (
            <motion.div
              key={goal.name}
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: index * 0.1 }}
            >
              <div className="flex items-center justify-between mb-1">
                <span className="text-sm font-medium dark:text-white">{goal.name}</span>
                <div className="flex items-center gap-1">
                  <span className="text-sm text-muted-foreground">{goal.progress}%</span>
                  {getTrendIcon(goal.trend)}
                </div>
              </div>
              <Progress value={goal.progress} className="h-2" />
            </motion.div>
          ))}
        </div>
      </Card>

      {/* Highlights & Challenges */}
      <div className="grid md:grid-cols-2 gap-4">
        {/* Highlights */}
        <Card className="p-6">
          <h3 className="font-semibold mb-4 flex items-center gap-2 text-green-700 dark:text-green-400">
            <Award className="w-5 h-5" />
            This Week's Wins
          </h3>
          <ul className="space-y-3">
            {summary.highlights.map((highlight, index) => (
              <motion.li
                key={index}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
                className="flex items-start gap-2"
              >
                <CheckCircle2 className="w-4 h-4 text-green-500 mt-0.5 flex-shrink-0" />
                <span className="text-sm text-gray-600 dark:text-gray-300">{highlight}</span>
              </motion.li>
            ))}
          </ul>
        </Card>

        {/* Challenges */}
        <Card className="p-6">
          <h3 className="font-semibold mb-4 flex items-center gap-2 text-amber-700 dark:text-amber-400">
            <AlertCircle className="w-5 h-5" />
            Areas to Focus On
          </h3>
          <ul className="space-y-3">
            {summary.challenges.map((challenge, index) => (
              <motion.li
                key={index}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
                className="flex items-start gap-2"
              >
                <Heart className="w-4 h-4 text-amber-500 mt-0.5 flex-shrink-0" />
                <span className="text-sm text-gray-600 dark:text-gray-300">{challenge}</span>
              </motion.li>
            ))}
          </ul>
        </Card>
      </div>

      {/* Recommendations */}
      <Card className="p-6 bg-gradient-to-r from-teal-50 to-cyan-50 dark:from-teal-900/20 dark:to-cyan-900/20 border-teal-200 dark:border-teal-800">
        <h3 className="font-semibold mb-4 flex items-center gap-2 text-teal-700 dark:text-teal-400">
          <Lightbulb className="w-5 h-5" />
          AI Recommendations for Next Week
        </h3>
        <ul className="space-y-3">
          {summary.recommendations.map((rec, index) => (
            <motion.li
              key={index}
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: index * 0.15 }}
              className="flex items-start gap-3 p-3 bg-white dark:bg-slate-800 rounded-lg"
            >
              <div className="w-6 h-6 bg-teal-100 dark:bg-teal-800 rounded-full flex items-center justify-center flex-shrink-0">
                <span className="text-xs font-bold text-teal-600 dark:text-teal-400">{index + 1}</span>
              </div>
              <span className="text-sm text-gray-700 dark:text-gray-300">{rec}</span>
            </motion.li>
          ))}
        </ul>
      </Card>
    </div>
  );
}

export default WeeklyAISummary;
