// Copyright (c) 2024-2026 Aminy LLC. All Rights Reserved.
// CONFIDENTIAL AND PROPRIETARY — Trade Secret of Aminy LLC
// Unauthorized use, reproduction, or distribution is strictly prohibited.
// See LICENSE file for details.

/**
 * WeeklyAISummary - AI-generated weekly insights and summaries
 *
 * Features:
 * - Weekly progress summary generated by AI
 * - Key insights and observations
 * - Trend detection
 * - Recommendations for the coming week
 * - Shareable summary card
 */

import React, { useState, useEffect } from 'react';
import { motion } from 'motion/react';
import {
  Sparkles,
  TrendingUp,
  TrendingDown,
  Minus,
  Target,
  Lightbulb,
  Share2,
  ChevronRight,
  Loader2,
  RefreshCw,
  Award,
  Heart,
  AlertCircle,
  CheckCircle2,
  Star,
  Mail
} from 'lucide-react';
import { Card } from './ui/card';
import { Button } from './ui/button';
import { Badge } from './ui/badge';
import { Progress } from './ui/progress';
import { toast } from 'sonner';
import { supabase } from '../utils/supabase/client';
import { projectId, publicAnonKey } from '../utils/supabase/info';
import { generateCaregiverSummary, getLatestCaregiverSummary } from '../lib/caregiver-workflow';

interface WeeklySummary {
  weekOf: string;
  overallProgress: number;
  progressTrend: 'up' | 'down' | 'stable';
  highlights: string[];
  challenges: string[];
  recommendations: string[];
  goalsProgress: {
    name: string;
    progress: number;
    trend: 'up' | 'down' | 'stable';
  }[];
  moodPattern: 'positive' | 'neutral' | 'challenging';
  streakDays: number;
  activitiesCompleted: number;
  conversationsCount: number;
}

interface WeeklyAISummaryProps {
  childName: string;
  childId?: string;
  onViewDetails?: () => void;
  compact?: boolean;
}

export function WeeklyAISummary({
  childName,
  childId,
  onViewDetails,
  compact = false
}: WeeklyAISummaryProps) {
  const [isLoading, setIsLoading] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);
  const [summary, setSummary] = useState<WeeklySummary | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    loadWeeklySummary();
  }, [childId]);

  const loadWeeklySummary = async () => {
    setIsLoading(true);
    setError(null);

    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;

      const latestSummary = await getLatestCaregiverSummary({
        userId: user.id,
        childId,
        periodStart: getWeekStart(),
      });

      if (latestSummary?.snapshot?.weeklySummary) {
        setSummary(latestSummary.snapshot.weeklySummary);
      } else {
        setSummary(null);
      }
    } catch (err) {
      console.error('Error loading summary:', err);
      setSummary(null);
    } finally {
      setIsLoading(false);
    }
  };

  const generateSummary = async () => {
    setIsGenerating(true);
    setError(null);

    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) {
        setError('Please sign in to generate your weekly summary.');
        return;
      }

      const generated = await generateCaregiverSummary({
        userId: user.id,
        childId,
        periodStart: getWeekStart(),
        forceRegenerate: true,
      });

      setSummary(generated.snapshot.weeklySummary);
      toast.success('Weekly insights generated from stored caregiver records.');
    } catch (err) {
      console.error('Error generating summary:', err);
      setError('Failed to generate summary. Please try again.');
      toast.error('Failed to generate summary');
    } finally {
      setIsGenerating(false);
    }
  };

  const getWeekStart = (): string => {
    const now = new Date();
    const dayOfWeek = now.getDay();
    const diff = now.getDate() - dayOfWeek + (dayOfWeek === 0 ? -6 : 1);
    const weekStart = new Date(now.setDate(diff));
    return weekStart.toISOString().split('T')[0];
  };

  const getTrendIcon = (trend: 'up' | 'down' | 'stable') => {
    switch (trend) {
      case 'up':
        return <TrendingUp className="w-4 h-4 text-green-500" />;
      case 'down':
        return <TrendingDown className="w-4 h-4 text-red-500" />;
      default:
        return <Minus className="w-4 h-4 text-[#8A9BA8]" />;
    }
  };

  const getMoodColor = (mood: string) => {
    switch (mood) {
      case 'positive':
        return 'bg-green-100 text-green-700 border-green-200';
      case 'challenging':
        return 'bg-amber-100 text-amber-700 border-amber-200';
      default:
        return 'bg-[#EDF4F7] text-[#3A4A57] border-[#E8E4DF]';
    }
  };

  const handleEmailRecap = async () => {
    if (!summary) return;
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user?.email) { toast.error('No email on file'); return; }
      const resp = await fetch(
        `https://${projectId}.supabase.co/functions/v1/make-server-8a022548/email/weekly-digest`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${publicAnonKey}` },
          body: JSON.stringify({
            email: user.email,
            userName: user.user_metadata?.full_name || 'Parent',
            childName,
            weekStats: {
              overallProgress: summary.overallProgress,
              highlights: summary.highlights,
              recommendations: summary.recommendations,
              streakDays: summary.streakDays,
              activitiesCompleted: summary.activitiesCompleted,
            },
          }),
        }
      );
      if (resp.ok) {
        toast.success(`Weekly recap sent to ${user.email}`);
      } else {
        toast.error('Could not send email — try again');
      }
    } catch {
      toast.error('Email delivery failed');
    }
  };

  const handleShare = async () => {
    if (!summary) return;

    const shareText = `
${childName}'s Weekly Progress Summary

Overall Progress: ${summary.overallProgress}%

Highlights:
${summary.highlights.map(h => `• ${h}`).join('\n')}

Keep up the great work! 🌟

Generated by Aminy
    `.trim();

    if (navigator.share) {
      try {
        await navigator.share({
          title: `${childName}'s Weekly Progress`,
          text: shareText
        });
      } catch (err) {
        // User cancelled or error
      }
    } else {
      await navigator.clipboard.writeText(shareText);
      toast.success('Summary copied to clipboard!');
    }
  };

  if (isLoading) {
    return (
      <Card className="p-6">
        <div className="flex items-center justify-center">
          <Loader2 className="w-6 h-6 animate-spin text-primary" />
          <span className="ml-2 text-muted-foreground">Loading insights...</span>
        </div>
      </Card>
    );
  }

  if (!summary) {
    return (
      <Card className="p-6 text-center">
        <Sparkles className="w-8 h-8 text-muted-foreground mx-auto mb-3" />
        <p className="text-muted-foreground mb-2">No summary available yet</p>
        {error && (
          <p className="text-sm text-red-500 mb-4">{error}</p>
        )}
        <p className="text-sm text-muted-foreground mb-4">
          Generate an AI-powered summary of your child's progress from the past week
        </p>
        <Button onClick={generateSummary} disabled={isGenerating}>
          {isGenerating ? (
            <>
              <Loader2 className="w-4 h-4 mr-2 animate-spin" />
              Analyzing this week's data...
            </>
          ) : (
            <>
              <Sparkles className="w-4 h-4 mr-2" />
              Generate Weekly Summary
            </>
          )}
        </Button>
      </Card>
    );
  }

  // Compact version for dashboard
  if (compact) {
    return (
      <Card className="p-4 hover:shadow-md transition-shadow cursor-pointer" onClick={onViewDetails}>
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-gradient-to-br from-[#2A7D99] to-[#6B9080] rounded-lg flex items-center justify-center">
              <Sparkles className="w-4 h-4 text-white" />
            </div>
            <div>
              <h3 className="font-semibold text-sm dark:text-white">Weekly Insights</h3>
              <p className="text-sm text-muted-foreground">Week of {new Date(summary.weekOf).toLocaleDateString()}</p>
            </div>
          </div>
          <div className="flex items-center gap-1">
            <span className="text-lg font-bold text-[#6B9080]">{summary.overallProgress}%</span>
            {getTrendIcon(summary.progressTrend)}
          </div>
        </div>

        <div className="space-y-2">
          <div className="flex items-center gap-2 text-sm">
            <CheckCircle2 className="w-4 h-4 text-green-500 flex-shrink-0" />
            <span className="text-[#5A6B7A] dark:text-gray-300 truncate">{summary.highlights[0]}</span>
          </div>
          {summary.recommendations[0] && (
            <div className="flex items-center gap-2 text-sm">
              <Lightbulb className="w-4 h-4 text-amber-500 flex-shrink-0" />
              <span className="text-[#5A6B7A] dark:text-gray-300 truncate">{summary.recommendations[0]}</span>
            </div>
          )}
        </div>

        <div className="flex items-center justify-between mt-3 pt-3 border-t border-[#E8E4DF] dark:border-slate-700">
          <div className="flex gap-3">
            <Badge variant="outline" className="text-sm">
              <Star className="w-3 h-3 mr-1" />
              {summary.streakDays} day streak
            </Badge>
            <Badge variant="outline" className={`text-sm ${getMoodColor(summary.moodPattern)}`}>
              {summary.moodPattern}
            </Badge>
          </div>
          <ChevronRight className="w-4 h-4 text-muted-foreground" />
        </div>
      </Card>
    );
  }

  // Full version
  return (
    <div className="space-y-6">
      {/* Header */}
      <Card className="p-6 bg-gradient-to-br from-[#EDF4F7] to-[#F6FBFB] dark:from-slate-800 dark:to-slate-700 border-[#D6E6EC] dark:border-slate-700">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 bg-gradient-to-br from-[#2A7D99] to-[#6B9080] rounded-xl flex items-center justify-center">
              <Sparkles className="w-6 h-6 text-white" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-xl font-semibold dark:text-white">Weekly Insights</h2>
                <Badge variant="outline" className="text-sm bg-amber-50 text-amber-700 border-amber-300">Preview</Badge>
              </div>
              <p className="text-sm text-muted-foreground">
                Week of {new Date(summary.weekOf).toLocaleDateString('en-US', { month: 'long', day: 'numeric' })}
              </p>
            </div>
          </div>

          <div className="flex gap-2">
            <Button variant="outline" size="sm" onClick={handleEmailRecap}>
              <Mail className="w-4 h-4 mr-1" />
              Email
            </Button>
            <Button variant="outline" size="sm" onClick={handleShare}>
              <Share2 className="w-4 h-4 mr-1" />
              Share
            </Button>
            <Button variant="outline" size="sm" onClick={generateSummary} disabled={isGenerating}>
              {isGenerating ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <RefreshCw className="w-4 h-4" />
              )}
            </Button>
          </div>
        </div>

        {/* Overall Progress */}
        <div className="flex items-center gap-4">
          <div className="flex-1">
            <div className="flex items-center justify-between mb-2">
              <span className="text-sm font-medium text-[#3A4A57] dark:text-gray-300">Overall Progress</span>
              <div className="flex items-center gap-1">
                <span className="text-2xl font-bold text-[#2A7D99] dark:text-[#7BA7BC]">{summary.overallProgress}%</span>
                {getTrendIcon(summary.progressTrend)}
              </div>
            </div>
            <Progress value={summary.overallProgress} className="h-3" />
          </div>
        </div>

        {/* Quick Stats */}
        <div className="grid grid-cols-3 gap-4 mt-4 pt-4 border-t border-[#D6E6EC] dark:border-slate-700">
          <div className="text-center">
            <p className="text-2xl font-bold text-[#2A7D99] dark:text-[#7BA7BC]">{summary.streakDays}</p>
            <p className="text-sm text-muted-foreground">Day Streak</p>
            <p className="text-sm text-[#8A9BA8] dark:text-slate-500 mt-0.5">Days in a row you checked in</p>
          </div>
          <div className="text-center">
            <p className="text-2xl font-bold text-[#2A7D99] dark:text-[#7BA7BC]">{summary.activitiesCompleted}</p>
            <p className="text-sm text-muted-foreground">Activities</p>
            <p className="text-sm text-[#8A9BA8] dark:text-slate-500 mt-0.5">Tools and routines you completed</p>
          </div>
          <div className="text-center">
            <p className="text-2xl font-bold text-[#2A7D99] dark:text-[#7BA7BC]">{summary.conversationsCount}</p>
            <p className="text-sm text-muted-foreground">AI Chats</p>
            <p className="text-sm text-[#8A9BA8] dark:text-slate-500 mt-0.5">Times you talked with Aminy</p>
          </div>
        </div>
      </Card>

      {/* Goals Progress */}
      <Card className="p-6">
        <h3 className="font-semibold mb-4 flex items-center gap-2 dark:text-white">
          <Target className="w-5 h-5 text-primary" />
          Goals Progress
        </h3>
        <div className="space-y-4">
          {summary.goalsProgress.map((goal, index) => (
            <motion.div
              key={goal.name}
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: index * 0.1 }}
            >
              <div className="flex items-center justify-between mb-1">
                <span className="text-sm font-medium dark:text-white">{goal.name}</span>
                <div className="flex items-center gap-1">
                  <span className="text-sm text-muted-foreground">{goal.progress}%</span>
                  {getTrendIcon(goal.trend)}
                </div>
              </div>
              <Progress value={goal.progress} className="h-2" />
            </motion.div>
          ))}
        </div>
      </Card>

      {/* Highlights & Challenges */}
      <div className="grid md:grid-cols-2 gap-4">
        {/* Highlights */}
        <Card className="p-6">
          <h3 className="font-semibold mb-4 flex items-center gap-2 text-green-700 dark:text-green-400">
            <Award className="w-5 h-5" />
            This Week's Wins
          </h3>
          <ul className="space-y-3">
            {summary.highlights.map((highlight, index) => (
              <motion.li
                key={`${index}-${highlight}`}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
                className="flex items-start gap-2"
              >
                <CheckCircle2 className="w-4 h-4 text-green-500 mt-0.5 flex-shrink-0" />
                <span className="text-sm text-[#5A6B7A] dark:text-gray-300">{highlight}</span>
              </motion.li>
            ))}
          </ul>
        </Card>

        {/* Challenges */}
        <Card className="p-6">
          <h3 className="font-semibold mb-4 flex items-center gap-2 text-amber-700 dark:text-amber-400">
            <AlertCircle className="w-5 h-5" />
            Areas to Focus On
          </h3>
          <ul className="space-y-3">
            {summary.challenges.map((challenge, index) => (
              <motion.li
                key={`${index}-${challenge}`}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
                className="flex items-start gap-2"
              >
                <Heart className="w-4 h-4 text-amber-500 mt-0.5 flex-shrink-0" />
                <span className="text-sm text-[#5A6B7A] dark:text-gray-300">{challenge}</span>
              </motion.li>
            ))}
          </ul>
        </Card>
      </div>

      {/* Recommendations */}
      <Card className="p-6 bg-gradient-to-r from-[#F6FBFB] to-cyan-50 dark:from-teal-900/20 dark:to-cyan-900/20 border-[#6B9080]/20 dark:border-[#6B9080]/30">
        <h3 className="font-semibold mb-4 flex items-center gap-2 text-[#6B9080] dark:text-primary">
          <Lightbulb className="w-5 h-5" />
          AI Recommendations for Next Week
        </h3>
        <ul className="space-y-3">
          {summary.recommendations.map((rec, index) => (
            <motion.li
              key={`${index}-${rec}`}
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: index * 0.15 }}
              className="flex items-start gap-3 p-3 bg-white dark:bg-slate-800 rounded-lg"
            >
              <div className="w-6 h-6 bg-[#6B9080]/10 dark:bg-teal-800 rounded-full flex items-center justify-center flex-shrink-0">
                <span className="text-sm font-bold text-[#6B9080] dark:text-primary">{index + 1}</span>
              </div>
              <span className="text-sm text-[#3A4A57] dark:text-gray-300">{rec}</span>
            </motion.li>
          ))}
        </ul>
      </Card>
    </div>
  );
}

export default WeeklyAISummary;
