// Copyright (c) 2024-2026 Aminy LLC. All Rights Reserved.
// CONFIDENTIAL AND PROPRIETARY — Trade Secret of Aminy LLC
// Unauthorized use, reproduction, or distribution is strictly prohibited.
// See LICENSE file for details.

import React, { useState, useEffect, useMemo } from 'react';
import { FileText, Download, TrendingUp, TrendingDown, Minus, Lock, Loader2, Share2, Calendar } from 'lucide-react';
import { Button } from './ui/button';
import { Card } from './ui/card';
import { Badge } from './ui/badge';
import jsPDF from 'jspdf';
import { TierType, hasFeature, getTierDisplayName } from '../lib/tier-utils';
import { supabase } from '../utils/supabase/client';

// ============================================================================
// Types
// ============================================================================

export interface WeeklyOutcomesData {
  childName: string;
  parentName: string;
  weekStart: Date;
  weekEnd: Date;

  // Key Metrics
  activitiesCompleted: number;
  activitiesPlanned: number;
  routineAdherence: number; // percentage
  stressLevelAvg: number; // 1-10
  stressLevelPrevWeek?: number;

  // Goals Progress
  goalsAchieved: number;
  goalsInProgress: number;

  // Highlights
  wins: string[];
  challenges: string[];

  // AI Insights (optional)
  aiInsights?: string;

  // Calm Coins (gamification)
  calmCoinsEarned?: number;
}

interface WeeklyOutcomesPDFProps {
  data?: WeeklyOutcomesData;
  tier?: TierType;
  onUpgrade?: () => void;
}

// ============================================================================
// PDF Generation
// ============================================================================

const AMINY_BLUE = '#6B9080';
const AMINY_GREEN = '#4E93A8';
const GRAY_600 = '#4B5563';
const GRAY_400 = '#9CA3AF';

function generateWeeklyOutcomesPDF(data: WeeklyOutcomesData): jsPDF {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);
  let yPos = margin;

  const formatDate = (date: Date) => date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  // Header
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(AMINY_BLUE);
  doc.text('Aminy', margin, yPos);
  yPos += 8;

  doc.setFontSize(16);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(GRAY_600);
  doc.text('Weekly Outcomes Report', margin, yPos);
  yPos += 10;

  // Period and child info
  doc.setFontSize(11);
  doc.setTextColor(GRAY_400);
  doc.text(`${formatDate(data.weekStart)} - ${formatDate(data.weekEnd)}`, margin, yPos);
  yPos += 6;
  doc.text(`Child: ${data.childName} | Parent: ${data.parentName}`, margin, yPos);
  yPos += 12;

  // Watermark
  doc.setFillColor(245, 245, 245);
  doc.roundedRect(margin, yPos, contentWidth, 10, 2, 2, 'F');
  doc.setFontSize(8);
  doc.setTextColor(GRAY_400);
  doc.text(`Generated by Aminy on ${new Date().toLocaleDateString()} | Expires in 7 days`, margin + 5, yPos + 6);
  yPos += 18;

  // Key Metrics Section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(AMINY_BLUE);
  doc.text('Weekly Snapshot', margin, yPos);
  yPos += 10;

  // Metrics Grid
  const metricBoxWidth = (contentWidth - 10) / 3;
  const metrics = [
    { label: 'Activities', value: `${data.activitiesCompleted}/${data.activitiesPlanned}`, subtext: 'Completed' },
    { label: 'Routine Adherence', value: `${data.routineAdherence}%`, subtext: 'Success rate' },
    { label: 'Stress Level', value: `${data.stressLevelAvg}/10`, subtext: data.stressLevelPrevWeek ? `vs ${data.stressLevelPrevWeek}/10 last week` : 'Average' }
  ];

  metrics.forEach((metric, idx) => {
    const xPos = margin + (idx * (metricBoxWidth + 5));
    doc.setDrawColor(AMINY_BLUE);
    doc.setLineWidth(0.3);
    doc.roundedRect(xPos, yPos, metricBoxWidth, 25, 2, 2, 'S');

    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(AMINY_GREEN);
    doc.text(metric.value, xPos + metricBoxWidth / 2, yPos + 12, { align: 'center' });

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(GRAY_600);
    doc.text(metric.label, xPos + metricBoxWidth / 2, yPos + 18, { align: 'center' });
    doc.setTextColor(GRAY_400);
    doc.text(metric.subtext, xPos + metricBoxWidth / 2, yPos + 22, { align: 'center' });
  });
  yPos += 35;

  // Goals Progress
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(AMINY_BLUE);
  doc.text('Goals Progress', margin, yPos);
  yPos += 8;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(GRAY_600);
  doc.text(`✓ ${data.goalsAchieved} goals achieved this week`, margin + 5, yPos);
  yPos += 6;
  doc.text(`→ ${data.goalsInProgress} goals in progress`, margin + 5, yPos);
  yPos += 12;

  // Wins Section
  if (data.wins.length > 0) {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(AMINY_GREEN);
    doc.text('This Week\'s Wins', margin, yPos);
    yPos += 8;

    data.wins.forEach(win => {
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(GRAY_600);
      const lines = doc.splitTextToSize(`★ ${win}`, contentWidth - 10);
      doc.text(lines, margin + 5, yPos);
      yPos += lines.length * 5 + 2;
    });
    yPos += 5;
  }

  // Challenges Section
  if (data.challenges.length > 0) {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor('#F59E0B');
    doc.text('Areas to Focus', margin, yPos);
    yPos += 8;

    data.challenges.forEach(challenge => {
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(GRAY_600);
      const lines = doc.splitTextToSize(`• ${challenge}`, contentWidth - 10);
      doc.text(lines, margin + 5, yPos);
      yPos += lines.length * 5 + 2;
    });
    yPos += 5;
  }

  // AI Insights
  if (data.aiInsights) {
    doc.setFillColor(240, 249, 255);
    doc.roundedRect(margin, yPos, contentWidth, 30, 3, 3, 'F');

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(AMINY_BLUE);
    doc.text('AI Insights', margin + 5, yPos + 8);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(GRAY_600);
    const insightLines = doc.splitTextToSize(data.aiInsights, contentWidth - 15);
    doc.text(insightLines, margin + 5, yPos + 15);
    yPos += 40;
  }

  // Calm Coins
  if (data.calmCoinsEarned && data.calmCoinsEarned > 0) {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(AMINY_GREEN);
    doc.text(`🪙 ${data.calmCoinsEarned} Calm Coins earned this week!`, margin, yPos);
    yPos += 12;
  }

  // Footer
  doc.setDrawColor(GRAY_400);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 8;

  doc.setFontSize(9);
  doc.setTextColor(GRAY_400);
  doc.text('This report is for informational purposes only. Share with your care team for best results.', margin, yPos);
  yPos += 5;
  doc.text('Generated by Aminy AI | support@aminy.ai | www.aminy.ai', margin, yPos);

  return doc;
}

// ============================================================================
// Component
// ============================================================================

export function WeeklyOutcomesPDF({ data, tier = 'free', onUpgrade }: WeeklyOutcomesPDFProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [realData, setRealData] = useState<WeeklyOutcomesData | null>(null);

  // Calculate date range
  const today = new Date();
  const weekStart = new Date(today.getTime() - 7 * 24 * 60 * 60 * 1000);
  const weekEnd = today;

  // Check if user has access (Core tier or above)
  const hasAccess = hasFeature(tier, 'full-reports');

  // Load real data from Supabase
  useEffect(() => {
    async function loadRealData() {
      try {
        const { data: { user } } = await supabase.auth.getUser();
        if (!user) return;

        const weekStartISO = weekStart.toISOString();

        const [profileRes, childRes, goalsRes, calmRes, milestonesRes] = await Promise.all([
          supabase.from('profiles').select('name').eq('id', user.id).single(),
          supabase.from('children').select('name').eq('user_id', user.id).limit(1).single(),
          supabase.from('goals').select('*').eq('user_id', user.id).eq('is_active', true),
          supabase.from('calm_tool_sessions').select('coins_earned, duration_seconds').eq('user_id', user.id).gte('completed_at', weekStartISO),
          supabase.from('user_milestones').select('milestone_type').eq('user_id', user.id).gte('achieved_at', weekStartISO),
        ]);

        const goals = goalsRes.data || [];
        const calmSessions = calmRes.data || [];
        const totalCoins = calmSessions.reduce((sum: number, s: { coins_earned?: number }) => sum + (s.coins_earned || 0), 0);
        const goalsAchieved = goals.filter((g: { progress?: number }) => (g.progress || 0) >= 100).length;

        setRealData({
          childName: childRes.data?.name || 'Child',
          parentName: profileRes.data?.name || 'Parent',
          weekStart,
          weekEnd,
          activitiesCompleted: calmSessions.length + goalsAchieved,
          activitiesPlanned: Math.max(goals.length + 5, calmSessions.length + goalsAchieved),
          routineAdherence: goals.length > 0 ? Math.round(goals.reduce((sum: number, g: { progress?: number }) => sum + (g.progress || 0), 0) / goals.length) : 0,
          stressLevelAvg: 4.0,
          goalsAchieved,
          goalsInProgress: goals.length - goalsAchieved,
          wins: (milestonesRes.data || []).map((m: { milestone_type: string }) => `Earned badge: ${m.milestone_type}`).slice(0, 3),
          challenges: [],
          calmCoinsEarned: totalCoins,
        });
      } catch { /* fall back to demo data */ }
    }
    loadRealData();
  }, []);

  // Use provided data > real data > demo data
  const reportData: WeeklyOutcomesData = useMemo(() => data || realData || {
    childName: 'Child',
    parentName: 'Parent',
    weekStart,
    weekEnd,
    activitiesCompleted: 12,
    activitiesPlanned: 15,
    routineAdherence: 85,
    stressLevelAvg: 4.2,
    stressLevelPrevWeek: 5.1,
    goalsAchieved: 3,
    goalsInProgress: 5,
    wins: [
      'Completed morning routine without prompts 3 days in a row',
      'Used calm-down strategies independently during frustration',
      'Made eye contact and said hi to a new friend at school'
    ],
    challenges: [
      'Evening transitions still challenging - try visual timer',
      'Homework focus decreased mid-week'
    ],
    aiInsights: 'Great progress this week! Morning routines are becoming more consistent. Consider adding a visual schedule for evening transitions to build on morning success.',
    calmCoinsEarned: 45
  }, [data, realData, weekStart, weekEnd]);

  const handleDownload = async () => {
    if (!hasAccess) {
      onUpgrade?.();
      return;
    }

    setIsGenerating(true);
    try {
      const doc = generateWeeklyOutcomesPDF(reportData);
      const filename = `aminy-weekly-outcomes-${reportData.childName.replace(/\s+/g, '-').toLowerCase()}-${today.toISOString().split('T')[0]}.pdf`;
      doc.save(filename);
    } catch (error) {
      console.error('Failed to generate PDF:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  const getStressTrend = () => {
    if (!reportData.stressLevelPrevWeek) return null;
    const diff = reportData.stressLevelAvg - reportData.stressLevelPrevWeek;
    if (diff < -0.5) return { icon: TrendingDown, color: 'text-green-600', label: 'Improving' };
    if (diff > 0.5) return { icon: TrendingUp, color: 'text-red-600', label: 'Rising' };
    return { icon: Minus, color: 'text-[#5A6B7A]', label: 'Stable' };
  };

  const stressTrend = getStressTrend();

  return (
    <Card className="p-4 sm:p-5 md:p-6">
      <div className="flex items-start justify-between mb-4">
        <div>
          <div className="flex items-center gap-2 mb-2">
            <h3 className="text-lg font-semibold">Weekly Outcomes PDF</h3>
            <Badge variant="outline" className="bg-[#EEF4F8] border-[#C8DDE8] text-blue-700">
              Core Tier
            </Badge>
          </div>
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <Calendar className="w-4 h-4" />
            <span>Last 7 days: {weekStart.toLocaleDateString()} - {weekEnd.toLocaleDateString()}</span>
          </div>
        </div>
        <div className="flex gap-2">
          {hasAccess ? (
            <>
              <Button variant="outline" size="sm" disabled>
                <Share2 className="w-4 h-4 mr-2" />
                Share
              </Button>
              <Button onClick={handleDownload} disabled={isGenerating}>
                {isGenerating ? (
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                ) : (
                  <Download className="w-4 h-4 mr-2" />
                )}
                {isGenerating ? 'Generating...' : 'Download PDF'}
              </Button>
            </>
          ) : (
            <Button onClick={onUpgrade} variant="outline">
              <Lock className="w-4 h-4 mr-2" />
              Upgrade to {getTierDisplayName('core')}
            </Button>
          )}
        </div>
      </div>

      {/* Preview Metrics */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3 sm:gap-4">
        <div className="p-4 bg-gradient-to-br from-blue-50 to-blue-100 rounded-lg">
          <p className="text-xl sm:text-2xl font-bold text-blue-700">
            {reportData.activitiesCompleted}/{reportData.activitiesPlanned}
          </p>
          <p className="text-sm text-blue-600">Activities Completed</p>
        </div>
        <div className="p-4 bg-gradient-to-br from-green-50 to-green-100 rounded-lg">
          <p className="text-xl sm:text-2xl font-bold text-green-700">{reportData.routineAdherence}%</p>
          <p className="text-sm text-green-600">Routine Adherence</p>
        </div>
        <div className="p-4 bg-gradient-to-br from-purple-50 to-purple-100 rounded-lg">
          <p className="text-xl sm:text-2xl font-bold text-purple-700">{reportData.goalsAchieved}</p>
          <p className="text-sm text-purple-600">Goals Achieved</p>
        </div>
        <div className="p-4 bg-gradient-to-br from-amber-50 to-amber-100 rounded-lg">
          <div className="flex items-center gap-1">
            <p className="text-xl sm:text-2xl font-bold text-amber-700">{reportData.stressLevelAvg.toFixed(1)}</p>
            {stressTrend && (
              <stressTrend.icon className={`w-4 h-4 ${stressTrend.color}`} />
            )}
          </div>
          <p className="text-sm text-amber-600">
            Stress Level {stressTrend && `(${stressTrend.label})`}
          </p>
        </div>
      </div>

      {/* Wins Preview */}
      {reportData.wins.length > 0 && (
        <div className="mt-4 p-4 bg-green-50 rounded-lg border border-green-100">
          <p className="font-medium text-green-800 mb-2">This Week's Wins</p>
          <ul className="text-sm text-green-700 space-y-1">
            {reportData.wins.slice(0, 2).map((win, idx) => (
              <li key={idx} className="flex items-start gap-2">
                <span>★</span>
                <span>{win}</span>
              </li>
            ))}
            {reportData.wins.length > 2 && (
              <li className="text-green-600">+{reportData.wins.length - 2} more wins in full report</li>
            )}
          </ul>
        </div>
      )}

      {/* Tier Gate Message */}
      {!hasAccess && (
        <div className="mt-4 p-4 bg-amber-50 rounded-lg border border-amber-200">
          <p className="text-sm text-amber-800">
            <strong>Upgrade to Core</strong> to download polished PDF reports with charts, insights, and shareable summaries.
          </p>
        </div>
      )}
    </Card>
  );
}
