/**
 * WeeklyAISummary - AI-generated weekly insights and summaries
 *
 * Features:
 * - Weekly progress summary generated by AI
 * - Key insights and observations
 * - Trend detection
 * - Recommendations for the coming week
 * - Shareable summary card
 */

import React, { useState, useEffect } from 'react';
import { motion } from 'motion/react';
import {
  Sparkles,
  TrendingUp,
  TrendingDown,
  Minus,
  Calendar,
  Target,
  Lightbulb,
  ArrowRight,
  Share2,
  Download,
  ChevronRight,
  Loader2,
  RefreshCw,
  Award,
  Heart,
  AlertCircle,
  CheckCircle2,
  Star
} from 'lucide-react';
import { Card } from './ui/card';
import { Button } from './ui/button';
import { Badge } from './ui/badge';
import { Progress } from './ui/progress';
import { toast } from 'sonner';
import { supabase } from '../utils/supabase/client';

interface WeeklySummary {
  weekOf: string;
  overallProgress: number;
  progressTrend: 'up' | 'down' | 'stable';
  highlights: string[];
  challenges: string[];
  recommendations: string[];
  goalsProgress: {
    name: string;
    progress: number;
    trend: 'up' | 'down' | 'stable';
  }[];
  moodPattern: 'positive' | 'neutral' | 'challenging';
  streakDays: number;
  activitiesCompleted: number;
  conversationsCount: number;
}

interface WeeklyAISummaryProps {
  childName: string;
  childId?: string;
  onViewDetails?: () => void;
  compact?: boolean;
}

export function WeeklyAISummary({
  childName,
  childId,
  onViewDetails,
  compact = false
}: WeeklyAISummaryProps) {
  const [isLoading, setIsLoading] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);
  const [summary, setSummary] = useState<WeeklySummary | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    loadWeeklySummary();
  }, [childId]);

  const loadWeeklySummary = async () => {
    setIsLoading(true);
    setError(null);

    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;

      // Try to load cached summary
      const weekStart = getWeekStart();
      const { data: cachedSummary } = await supabase
        .from('weekly_summaries')
        .select('*')
        .eq('user_id', user.id)
        .eq('week_of', weekStart)
        .single();

      if (cachedSummary) {
        setSummary(parseSummary(cachedSummary));
      } else {
        // Generate new summary
        await generateSummary();
      }
    } catch (err) {
      console.error('Error loading summary:', err);
      // Use mock data for demo
      setSummary(getMockSummary());
    } finally {
      setIsLoading(false);
    }
  };

  const generateSummary = async () => {
    setIsGenerating(true);

    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;

      // In production, this would call the AI to analyze the week's data
      // For now, we'll generate a mock summary
      const newSummary = getMockSummary();
      setSummary(newSummary);

      // Cache the summary
      await supabase
        .from('weekly_summaries')
        .upsert({
          user_id: user.id,
          week_of: getWeekStart(),
          summary_data: newSummary,
          generated_at: new Date().toISOString()
        });

      toast.success('Weekly insights generated!');
    } catch (err) {
      console.error('Error generating summary:', err);
      toast.error('Failed to generate summary');
    } finally {
      setIsGenerating(false);
    }
  };

  const getWeekStart = (): string => {
    const now = new Date();
    const dayOfWeek = now.getDay();
    const diff = now.getDate() - dayOfWeek + (dayOfWeek === 0 ? -6 : 1);
    const weekStart = new Date(now.setDate(diff));
    return weekStart.toISOString().split('T')[0];
  };

  const parseSummary = (data: any): WeeklySummary => {
    return data.summary_data as WeeklySummary;
  };

  const getMockSummary = (): WeeklySummary => {
    return {
      weekOf: getWeekStart(),
      overallProgress: 72,
      progressTrend: 'up',
      highlights: [
        `${childName} completed 85% of morning routine independently this week`,
        'Showed improved emotional regulation during transitions',
        'Used communication board 12 times to express needs'
      ],
      challenges: [
        'Bedtime routine still requires additional support',
        'Some sensory sensitivity to loud environments'
      ],
      recommendations: [
        'Continue the visual timer strategy - it\'s working well for transitions',
        'Try introducing a "calm down corner" with sensory tools before bed',
        'Consider noise-reducing headphones for challenging environments'
      ],
      goalsProgress: [
        { name: 'Morning Independence', progress: 85, trend: 'up' },
        { name: 'Communication', progress: 68, trend: 'up' },
        { name: 'Emotional Regulation', progress: 55, trend: 'stable' },
        { name: 'Social Skills', progress: 45, trend: 'up' }
      ],
      moodPattern: 'positive',
      streakDays: 5,
      activitiesCompleted: 28,
      conversationsCount: 15
    };
  };

  const getTrendIcon = (trend: 'up' | 'down' | 'stable') => {
    switch (trend) {
      case 'up':
        return <TrendingUp className="w-4 h-4 text-green-500" />;
      case 'down':
        return <TrendingDown className="w-4 h-4 text-red-500" />;
      default:
        return <Minus className="w-4 h-4 text-gray-400" />;
    }
  };

  const getMoodColor = (mood: string) => {
    switch (mood) {
      case 'positive':
        return 'bg-green-100 text-green-700 border-green-200';
      case 'challenging':
        return 'bg-amber-100 text-amber-700 border-amber-200';
      default:
        return 'bg-gray-100 text-gray-700 border-gray-200';
    }
  };

  const handleShare = async () => {
    if (!summary) return;

    const shareText = `
${childName}'s Weekly Progress Summary

Overall Progress: ${summary.overallProgress}%

Highlights:
${summary.highlights.map(h => `• ${h}`).join('\n')}

Keep up the great work! 🌟

Generated by Aminy
    `.trim();

    if (navigator.share) {
      try {
        await navigator.share({
          title: `${childName}'s Weekly Progress`,
          text: shareText
        });
      } catch (err) {
        // User cancelled or error
      }
    } else {
      await navigator.clipboard.writeText(shareText);
      toast.success('Summary copied to clipboard!');
    }
  };

  if (isLoading) {
    return (
      <Card className="p-6">
        <div className="flex items-center justify-center">
          <Loader2 className="w-6 h-6 animate-spin text-teal-500" />
          <span className="ml-2 text-muted-foreground">Loading insights...</span>
        </div>
      </Card>
    );
  }

  if (!summary) {
    return (
      <Card className="p-6 text-center">
        <Sparkles className="w-8 h-8 text-muted-foreground mx-auto mb-3" />
        <p className="text-muted-foreground mb-4">No summary available yet</p>
        <Button onClick={generateSummary} disabled={isGenerating}>
          {isGenerating ? (
            <>
              <Loader2 className="w-4 h-4 mr-2 animate-spin" />
              Generating...
            </>
          ) : (
            <>
              <Sparkles className="w-4 h-4 mr-2" />
              Generate Weekly Summary
            </>
          )}
        </Button>
      </Card>
    );
  }

  // Compact version for dashboard
  if (compact) {
    return (
      <Card className="p-4 hover:shadow-md transition-shadow cursor-pointer" onClick={onViewDetails}>
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-gradient-to-br from-purple-500 to-pink-500 rounded-lg flex items-center justify-center">
              <Sparkles className="w-4 h-4 text-white" />
            </div>
            <div>
              <h3 className="font-semibold text-sm dark:text-white">Weekly Insights</h3>
              <p className="text-xs text-muted-foreground">Week of {new Date(summary.weekOf).toLocaleDateString()}</p>
            </div>
          </div>
          <div className="flex items-center gap-1">
            <span className="text-lg font-bold text-teal-600">{summary.overallProgress}%</span>
            {getTrendIcon(summary.progressTrend)}
          </div>
        </div>

        <div className="space-y-2">
          <div className="flex items-center gap-2 text-sm">
            <CheckCircle2 className="w-4 h-4 text-green-500 flex-shrink-0" />
            <span className="text-gray-600 dark:text-gray-300 truncate">{summary.highlights[0]}</span>
          </div>
          {summary.recommendations[0] && (
            <div className="flex items-center gap-2 text-sm">
              <Lightbulb className="w-4 h-4 text-amber-500 flex-shrink-0" />
              <span className="text-gray-600 dark:text-gray-300 truncate">{summary.recommendations[0]}</span>
            </div>
          )}
        </div>

        <div className="flex items-center justify-between mt-3 pt-3 border-t border-gray-100 dark:border-slate-700">
          <div className="flex gap-3">
            <Badge variant="outline" className="text-xs">
              <Star className="w-3 h-3 mr-1" />
              {summary.streakDays} day streak
            </Badge>
            <Badge variant="outline" className={`text-xs ${getMoodColor(summary.moodPattern)}`}>
              {summary.moodPattern}
            </Badge>
          </div>
          <ChevronRight className="w-4 h-4 text-muted-foreground" />
        </div>
      </Card>
    );
  }

  // Full version
  return (
    <div className="space-y-6">
      {/* Header */}
      <Card className="p-6 bg-gradient-to-br from-purple-50 to-pink-50 dark:from-purple-900/20 dark:to-pink-900/20 border-purple-200 dark:border-purple-800">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 bg-gradient-to-br from-purple-500 to-pink-500 rounded-xl flex items-center justify-center">
              <Sparkles className="w-6 h-6 text-white" />
            </div>
            <div>
              <h2 className="text-xl font-semibold dark:text-white">Weekly Insights</h2>
              <p className="text-sm text-muted-foreground">
                Week of {new Date(summary.weekOf).toLocaleDateString('en-US', { month: 'long', day: 'numeric' })}
              </p>
            </div>
          </div>

          <div className="flex gap-2">
            <Button variant="outline" size="sm" onClick={handleShare}>
              <Share2 className="w-4 h-4 mr-1" />
              Share
            </Button>
            <Button variant="outline" size="sm" onClick={generateSummary} disabled={isGenerating}>
              {isGenerating ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <RefreshCw className="w-4 h-4" />
              )}
            </Button>
          </div>
        </div>

        {/* Overall Progress */}
        <div className="flex items-center gap-4">
          <div className="flex-1">
            <div className="flex items-center justify-between mb-2">
              <span className="text-sm font-medium text-gray-700 dark:text-gray-300">Overall Progress</span>
              <div className="flex items-center gap-1">
                <span className="text-2xl font-bold text-purple-600 dark:text-purple-400">{summary.overallProgress}%</span>
                {getTrendIcon(summary.progressTrend)}
              </div>
            </div>
            <Progress value={summary.overallProgress} className="h-3" />
          </div>
        </div>

        {/* Quick Stats */}
        <div className="grid grid-cols-3 gap-4 mt-4 pt-4 border-t border-purple-200 dark:border-purple-700">
          <div className="text-center">
            <p className="text-2xl font-bold text-purple-600 dark:text-purple-400">{summary.streakDays}</p>
            <p className="text-xs text-muted-foreground">Day Streak</p>
          </div>
          <div className="text-center">
            <p className="text-2xl font-bold text-purple-600 dark:text-purple-400">{summary.activitiesCompleted}</p>
            <p className="text-xs text-muted-foreground">Activities</p>
          </div>
          <div className="text-center">
            <p className="text-2xl font-bold text-purple-600 dark:text-purple-400">{summary.conversationsCount}</p>
            <p className="text-xs text-muted-foreground">AI Chats</p>
          </div>
        </div>
      </Card>

      {/* Goals Progress */}
      <Card className="p-6">
        <h3 className="font-semibold mb-4 flex items-center gap-2 dark:text-white">
          <Target className="w-5 h-5 text-teal-500" />
          Goals Progress
        </h3>
        <div className="space-y-4">
          {summary.goalsProgress.map((goal, index) => (
            <motion.div
              key={goal.name}
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: index * 0.1 }}
            >
              <div className="flex items-center justify-between mb-1">
                <span className="text-sm font-medium dark:text-white">{goal.name}</span>
                <div className="flex items-center gap-1">
                  <span className="text-sm text-muted-foreground">{goal.progress}%</span>
                  {getTrendIcon(goal.trend)}
                </div>
              </div>
              <Progress value={goal.progress} className="h-2" />
            </motion.div>
          ))}
        </div>
      </Card>

      {/* Highlights & Challenges */}
      <div className="grid md:grid-cols-2 gap-4">
        {/* Highlights */}
        <Card className="p-6">
          <h3 className="font-semibold mb-4 flex items-center gap-2 text-green-700 dark:text-green-400">
            <Award className="w-5 h-5" />
            This Week's Wins
          </h3>
          <ul className="space-y-3">
            {summary.highlights.map((highlight, index) => (
              <motion.li
                key={index}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
                className="flex items-start gap-2"
              >
                <CheckCircle2 className="w-4 h-4 text-green-500 mt-0.5 flex-shrink-0" />
                <span className="text-sm text-gray-600 dark:text-gray-300">{highlight}</span>
              </motion.li>
            ))}
          </ul>
        </Card>

        {/* Challenges */}
        <Card className="p-6">
          <h3 className="font-semibold mb-4 flex items-center gap-2 text-amber-700 dark:text-amber-400">
            <AlertCircle className="w-5 h-5" />
            Areas to Focus On
          </h3>
          <ul className="space-y-3">
            {summary.challenges.map((challenge, index) => (
              <motion.li
                key={index}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
                className="flex items-start gap-2"
              >
                <Heart className="w-4 h-4 text-amber-500 mt-0.5 flex-shrink-0" />
                <span className="text-sm text-gray-600 dark:text-gray-300">{challenge}</span>
              </motion.li>
            ))}
          </ul>
        </Card>
      </div>

      {/* Recommendations */}
      <Card className="p-6 bg-gradient-to-r from-teal-50 to-cyan-50 dark:from-teal-900/20 dark:to-cyan-900/20 border-teal-200 dark:border-teal-800">
        <h3 className="font-semibold mb-4 flex items-center gap-2 text-teal-700 dark:text-teal-400">
          <Lightbulb className="w-5 h-5" />
          AI Recommendations for Next Week
        </h3>
        <ul className="space-y-3">
          {summary.recommendations.map((rec, index) => (
            <motion.li
              key={index}
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: index * 0.15 }}
              className="flex items-start gap-3 p-3 bg-white dark:bg-slate-800 rounded-lg"
            >
              <div className="w-6 h-6 bg-teal-100 dark:bg-teal-800 rounded-full flex items-center justify-center flex-shrink-0">
                <span className="text-xs font-bold text-teal-600 dark:text-teal-400">{index + 1}</span>
              </div>
              <span className="text-sm text-gray-700 dark:text-gray-300">{rec}</span>
            </motion.li>
          ))}
        </ul>
      </Card>
    </div>
  );
}

export default WeeklyAISummary;
