// Copyright (c) 2024-2026 Aminy LLC. All Rights Reserved.
// CONFIDENTIAL AND PROPRIETARY — Trade Secret of Aminy LLC
// Unauthorized use, reproduction, or distribution is strictly prohibited.
// See LICENSE file for details.

/**
 * PDF Report Generator
 * Generates professional PDF reports for parents and providers
 * Uses simple HTML-to-text approach compatible with Deno Edge Functions
 */

interface ReportData {
  childId: string;
  childName?: string;
  reportType: string;
  startDate: string;
  endDate: string;
  totalActivities?: number;
  goalsProgress?: number;
  sessionsCompleted?: number;
  milestones?: string[];
  watermark?: string;
}

/**
 * Generate a PDF report as a Uint8Array
 * This is a simple text-based implementation for Deno
 * In production, integrate with a PDF library like pdfmake or puppeteer
 */
export function generatePDFReport(data: ReportData): Uint8Array {
  const {
    childId,
    childName = 'Child',
    reportType,
    startDate,
    endDate,
    totalActivities = 0,
    goalsProgress = 0,
    sessionsCompleted = 0,
    milestones = [],
    watermark
  } = data;

  // Format dates
  const formattedStart = new Date(startDate).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  const formattedEnd = new Date(endDate).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  // Get report title and description based on type
  const reportInfo = getReportInfo(reportType);

  // Generate report content
  const content = `
================================================================================
                                AMINY REPORT
                          ${reportInfo.title}
================================================================================

${watermark ? `\n${watermark}\n` : ''}

Child: ${childName}
Report Period: ${formattedStart} - ${formattedEnd}
Generated: ${new Date().toLocaleDateString('en-US', { 
  year: 'numeric', 
  month: 'long', 
  day: 'numeric',
  hour: '2-digit',
  minute: '2-digit'
})}

================================================================================
                              PROGRESS SUMMARY
================================================================================

Activities Completed: ${totalActivities}
Goal Progress Steps: ${goalsProgress}
Therapy Sessions: ${sessionsCompleted}

${milestones.length > 0 ? `
================================================================================
                             MILESTONES ACHIEVED
================================================================================

${milestones.map((m, i) => `${i + 1}. ${m}`).join('\n')}
` : ''}

================================================================================
                              CLINICAL NOTES
================================================================================

${reportInfo.notes}

${reportType === 'parent' ? `
================================================================================
                            WHAT THIS MEANS
================================================================================

Every small step forward matters. ${childName} is making progress at their own
pace, and that's exactly what we want to see. Keep showing up, keep trying
new strategies, and celebrate the wins—no matter how small they seem.

You're doing an amazing job. 💙

` : ''}

${reportType === 'provider' || reportType === 'iep' || reportType === 'bcba' ? `
================================================================================
                         RECOMMENDATIONS
================================================================================

1. Continue current intervention strategies with documented success
2. Monitor progress weekly and adjust as needed
3. Maintain consistent routines and visual supports
4. Schedule follow-up assessment in 30 days

` : ''}

${reportType === 'insurance' ? `
================================================================================
                       MEDICAL NECESSITY STATEMENT
================================================================================

This child requires ongoing therapeutic intervention to address developmental
delays and behavioral challenges. Progress is being made with consistent
support, and continued services are medically necessary to maintain gains
and achieve developmental milestones.

Supporting documentation and session notes available upon request.

` : ''}

================================================================================

Generated by Aminy AI - Your Compassionate Care Companion
This report is confidential and intended for the recipient only.

For questions or to request additional documentation:
support@aminy.ai | www.aminy.ai

================================================================================
`;

  // Convert to Uint8Array
  const encoder = new TextEncoder();
  return encoder.encode(content);
}

function getReportInfo(reportType: string): { title: string; notes: string } {
  switch (reportType) {
    case 'parent':
      return {
        title: 'Parent Progress Summary',
        notes: `This report provides an overview of your child's progress during the specified
period. All data is collected through daily activities, therapy sessions, and
milestone tracking within the Aminy platform.`
      };
    
    case 'provider':
      return {
        title: 'Provider Clinical Report',
        notes: `Clinical summary for professional review. Data includes structured observations,
activity completion rates, behavioral patterns, and developmental milestones
tracked through parent-reported activities and therapist sessions.`
      };
    
    case 'iep':
      return {
        title: 'IEP Progress Report',
        notes: `This report documents progress toward Individualized Education Program (IEP)
goals. Data is compiled from daily activities, therapy sessions, and parent
observations. All information should be reviewed in conjunction with formal
assessments and clinical evaluations.`
      };
    
    case 'progress':
      return {
        title: 'Developmental Progress Report',
        notes: `Comprehensive overview of developmental progress across multiple domains
including communication, social skills, sensory processing, and daily
living skills. Data reflects consistent tracking and parent engagement.`
      };
    
    case 'bcba':
      return {
        title: 'BCBA Clinical Notes',
        notes: `Board Certified Behavior Analyst (BCBA) session notes and progress documentation.
Includes behavioral observations, intervention strategies, data collection,
and recommendations for ongoing treatment.`
      };
    
    case 'insurance':
      return {
        title: 'Insurance Documentation Letter',
        notes: `Medical necessity documentation for insurance authorization. This letter
summarizes the child's therapeutic needs, current interventions, progress
made, and justification for continued services.`
      };
    
    default:
      return {
        title: 'Progress Report',
        notes: `General progress report documenting activities and milestones.`
      };
  }
}

/**
 * Generate HTML version of report (for future email integration)
 */
export function generateHTMLReport(data: ReportData): string {
  const {
    childName = 'Child',
    reportType,
    startDate,
    endDate,
    totalActivities = 0,
    goalsProgress = 0,
    sessionsCompleted = 0,
    milestones = [],
    watermark
  } = data;

  const formattedStart = new Date(startDate).toLocaleDateString();
  const formattedEnd = new Date(endDate).toLocaleDateString();
  const reportInfo = getReportInfo(reportType);

  return `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #1e293b; }
    h1 { color: #0891b2; border-bottom: 3px solid #0891b2; padding-bottom: 10px; }
    h2 { color: #334155; margin-top: 30px; }
    .watermark { background: #fef3c7; border-left: 4px solid #f59e0b; padding: 15px; margin: 20px 0; }
    .metric { display: inline-block; margin: 10px 20px; padding: 15px; background: #f1f5f9; border-radius: 8px; }
    .metric-value { font-size: 32px; font-weight: bold; color: #0891b2; }
    .metric-label { font-size: 14px; color: #64748b; }
    .milestone { padding: 10px; margin: 5px 0; background: #ecfdf5; border-left: 3px solid #10b981; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #64748b; }
  </style>
</head>
<body>
  <h1>Aminy ${reportInfo.title}</h1>
  
  ${watermark ? `<div class="watermark"><strong>${watermark}</strong></div>` : ''}
  
  <p><strong>Child:</strong> ${childName}</p>
  <p><strong>Report Period:</strong> ${formattedStart} - ${formattedEnd}</p>
  <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
  
  <h2>Progress Summary</h2>
  <div>
    <div class="metric">
      <div class="metric-value">${totalActivities}</div>
      <div class="metric-label">Activities</div>
    </div>
    <div class="metric">
      <div class="metric-value">${goalsProgress}</div>
      <div class="metric-label">Goal Steps</div>
    </div>
    <div class="metric">
      <div class="metric-value">${sessionsCompleted}</div>
      <div class="metric-label">Sessions</div>
    </div>
  </div>
  
  ${milestones.length > 0 ? `
    <h2>Milestones Achieved</h2>
    ${milestones.map(m => `<div class="milestone">${m}</div>`).join('')}
  ` : ''}
  
  <h2>Clinical Notes</h2>
  <p>${reportInfo.notes}</p>
  
  <div class="footer">
    <p>Generated by Aminy AI - Your Compassionate Care Companion</p>
    <p>This report is confidential and intended for the recipient only.</p>
    <p>For questions: support@aminy.ai | www.aminy.ai</p>
  </div>
</body>
</html>
  `;
}
